### ISSUE TITLE
A second way to declare options

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#10]
Currently (Before and for v1.0.0), options were/are declared like this:

```
entity A
entity B
entity C

paginate * with Something except A
paginate A with SomethingElse
```

The second way consists in copying the way the relationships are declared so that this syntax is added:

```
entity A
entity B
entity C

paginate {
    * with Something except A,
    A with SomethingElse
}
```

We wouldn't have to write the option's type every time we want to add an option to an entity.

**Comment by deepu105** [comment]
Could you hold on with this. We need to discuss

**Comment by MathieuAA** [comment]
Deepu, I'll postpone this for another time. After releasing v2.0.0 of JUML, I'll work on another huge project, so this can wait as it's not on my todo-urgently list.

**Comment by MathieuAA** [comment]
Closing this, we don't need that now.
