### ISSUE TITLE
in nosql mode(mongodb), jdl can support Map filed type? 

### ISSUE THREAD

**Issue by gemron** [jhipster/jhipster-core#100]
example:
entity Device {
	sn String,
	type String,
	appId String,
        conf **Map**
}
This eneity 's conf is a json document ,in mongo  we can save and use it , but jdl not support

**Comment by jdubois** [comment]
We don't plan to support this for the moment.

**Comment by gemron** [comment]
@jdubois  thank you for your answer.
I have another question, When i importing JDL, How to merge the current Entity Java Code, when the Entity have I custom Map type field?

**Comment by MathieuAA** [comment]
I'm not sure I understand your question, but I'l try to answer it. As mongo's map is a JSON document, you can always try to pass it as a string and parse it later but you would then be required to change the code so that it suits your needs.
