### ISSUE TITLE
Required relationships option

### ISSUE THREAD

**Issue by ddagnino** [jhipster/jhipster-core#107]
Hey guys,

Right now (at least looking at documentation page) there's no way to define a "required" relationship inside JDL, something that can easily be done with entity sub generator. If you want to have a full diagram with relationships but you also need to make them required you have to insert your jdl into the application and after that you have to modify the code to make it as required and also define the database fields as NOT NULL, or you can drop the relationship using the entity subgen and then recreate it adding the required option.

I know there's a workaround for this but it would be great to have this option.

Thanks.
Regards, Damian.

**Comment by MathieuAA** [comment]
Hi Damian, it is already available, but I may have forgot to document it in the docs...
To answer your question, just do:
```
relationship relationshipType {
  A {b required} to B {a required}
}
```
to have it working.

**Comment by MathieuAA** [comment]
A PR has been submitted to update the doc. Sorry for the inconvenience

**Comment by ddagnino** [comment]
Wow! Excellent! really quick response, thanks a lot, I just saw it in the documentation too.
