### ISSUE TITLE
HAS vs. USE relationships

### ISSUE THREAD

**Issue by toolforger** [jhipster/jhipster-core#108]
I hate it to proliferate these because relationships are a complex topic as it is, and I'd prefer a simple JDL over one with a lots of intricacies, but it can't be helped.

Technically, I need a way to specify CASCADE DELETE, for detail records that should be automatically deleted when the parent record is deleted.
Conceptually, this would be a "has" relationship. The classic 1:N INVOICE:INVOICE_ITEM relationship. Usually there's a whole lot of things that you do want to do differently with these, such as fetching (one will usually want to preload the children with the parent), child removal (implies child deletion), commit (children and parent always go together).

The converse would be the "use" relationship. E.g. N:1 ADDRESS:COUNTRY. COUNTRY records exist independently of whether they're referenced from anywhere, all you can do with them is to establish or remove a link to them.

Maybe this already exists and I just didn't find a reference in the documentation.
Also, maybe relationships need to be classified in more categories than "has" and "use" - I can't remember having seen anything that doesn't fit, but then I haven't always categorized relationships.

**Comment by MathieuAA** [comment]
Hello! As far as I know, "has" and "use" are just "aggregation" and "composition". "Has", or "aggregation" means that a parent contains a collection of children. Their living or dying doesn't affect the parent.
Composition, on the other hand, is just the opposite.

JHipster (JDL included) supports required relationships. Now, if you want a `ON DELETE CASCADE`, this should be asked on the generator page so as to be supported for the right association types (if need be).
Can't you add what you want by hand?

**Comment by cbornet** [comment]
About cascade delete, see [policies](https://jhipster.github.io/policies/)
> Policy 1: technologies used by JHipster have their default configuration used as much as possible

And the default is not to cascade delete

This could be an option but
> Policy 2: only add options when there is sufficient added-value in the generated code

And I'm not sure there is sufficient value as it's easy to set manually.

**Comment by atomfrede** [comment]
Currently not sure, but I think jhipster generates a repository for each entity. When I get @toolforger correct he is aiming a DDD approach Oliver Gierke preaches: You have an ``InvoiceRepository`` but no ``InvoiceItemRepository`` as an item can not exits alone. @toolforger Did I get you correctly?

 I like the approach a a lot, but I think it might be to complicated and really depends on your concrete business and development practice, as jhipster should be a starting point I am not sure if we should or can it add to the generator.

**Comment by gmarziou** [comment]
Yes similat to Olvier Gierke's recommendations in https://github.com/olivergierke/spring-restbucks

**Comment by cbornet** [comment]
@atomfrede we could maybe generate the code accordingly when the relation is required

**Comment by atomfrede** [comment]
@cbornet Would be cool to say, JHipster complies to DDD concepts :1st_place_medal:

**Comment by cbornet** [comment]
:+1 but the issue has to be moved to the main generator

**Comment by toolforger** [comment]
I am trying to use JHipster as the Single Source of Truth for the data model.
(As far as I understand DDD, this is sort-of DDD for the data layer. It is not what I had in mind, though maybe DDD and SSoT overlap.)

To me, the point is that the JDL is a nice compact representation of the data model for documentation purposes, and it is better if the documentation and the implementation are automatically consistent.
`--regenerate` achieves that nicely, and the difference between "has" and "use" is important enough for any use case I ever encountered that I think it's worth adding.
(I know I have to reapply manual changes after `--regenerate`. Adding a has/use distinction would eliminate some of that work, but it's more of a side benefit, but we do have a working manual patching process. No more having to look up and arge the correct JPA cascade incantation would be the more important time saver to me.)

BTW I tend to avoid the term "aggregation" because its distinction from "association" is intentionally vague. I.e. "use" would be "association or aggregation" while "has" would be "composition".

**Comment by MathieuAA** [comment]
I don't agree with you... Anyway, no point for me in keeping this ticket open. @atomfrede @cbornet @gmarziou do you want me to keep it open, as an open discussion?

**Comment by toolforger** [comment]
@MathieuAA You asked me if I couldn't add the required settings by hand, to which I responded that it's awkward in JPA, and that I'd like to keep it all together ("Single Source of Truth" contains this and also that I want to regenerate from the JDL, as recommended on https://jhipster.github.io/jdl/).

I didn't get answers or questions for clarifications, so I don't know how to proceed on this issue.
Also, right now it looks like I have to drop JDL as "the" source of the data model and try something else (no real idea where to look first for that).

**Comment by cbornet** [comment]
To me, we have everything in the core /JDL to describe this situation. "has" = "required relationship" and "use" = "simple relationship". We could probably generate better code for required relationships (with CASCADE, change of repository structure, ...) but that's a main generator issue.
Unless I'm missing something, ...

**Comment by MathieuAA** [comment]
That's what I was going to say.

**Comment by toolforger** [comment]
Ah ok, I wasn't aware that "required" is supposed to deal with that.

**Comment by toolforger** [comment]
I did some more thinking on the issue.
Result: "required" and composition are NOT the same; in fact, all four combinations are possible:

Not required, not composition: User 1:n Role, Roles and Users exist independently and can be freely associated.
Not required but composition: User 1:0..1 Portrait: A User may have uploaded a Portrait, but that's optional; however, if the User is deleted, the Portrait should go as well.
Required but not composition: Address *:1 Country: Addresses exist independently of Countries, but each Address MUST have a country.
Required and composition: Client 1:1 IdentificationDocument, e.g. as required by law - if the Client is deleted, the IdentificationDocument must be deleted as well, but as long as the Client record is kept the IdentificationDocument must be kept.

Some more thinking tells me that the concepts are indeed orthogonal:
"required" means "a reference must exist", or "null is unacceptable".
"composition" implies "the reference will never change" (this does not prevent the reference from being null).

Did I go wrong somewhere?

**Comment by MathieuAA** [comment]
> "required" and composition are NOT the same

In this case, you're looking at more objects...

**Comment by MathieuAA** [comment]
By the way, you're right about `required`.
Composition means something else entirely: if A has a "composition relationship" with B (A -> B), then B's life is linked with A's. A needs B (or there are some serious design problems...)
