### ISSUE TITLE
Convert what's parsed by the PegJS parser to a JHipster application object

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#109]
Checklist:
  - [x] Create the object
  - [x] Fill the object in the JDL parser
  - [x] Test them both

**Comment by deepu105** [comment]
Is this done? What is the syntax? I think we need to make sure the core team is ok with the syntax before we make it public

**Comment by deepu105** [comment]
Can you please write to the dev mailing list with the proposed syntax please
