### ISSUE TITLE
JDL Studio could not parse constants declaration

### ISSUE THREAD

**Issue by clong365** [jhipster/jhipster-core#110]
When I paste the content of test file
https://github.com/jhipster/jhipster-core/blob/master/test/test_files/constants.jdl

in JDL Studio. 

The following error message emerge out.

![image](https://cloud.githubusercontent.com/assets/150419/23933386/322efe3a-0979-11e7-9379-f99bf8b66083.png)

**Comment by MathieuAA** [comment]
Hello, it seems the JDL studio is not up-to-date with the JDL. Can you open a new ticket in JDL studio's issue tracker please? thanks.

**Comment by deepu105** [comment]
JDL studio has been updated with latest version. Please check now @clong365

**Comment by clong365** [comment]
It's working properly now.

Thanks @deepu105
