### ISSUE TITLE
Support database reserved keywords

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#112]
As discussed [here](https://github.com/jhipster/generator-jhipster/issues/5427).

**Comment by gmarziou** [comment]
So should we always quote columns or only for reserved words?

**Comment by MathieuAA** [comment]
Only for the reserved keywords as far as I'm concerned.

**Comment by MathieuAA** [comment]
Julien is on that and has committed something, I'm closing this
