### ISSUE TITLE
Suggested date type in Oracle

### ISSUE THREAD

**Issue by BryanYin** [jhipster/jhipster-core#113]
Hi,
In JDL data mapping from Java to Oracle, we have now these date or time types:
LocalDate(Java) <=> 'date' (Oracle)
ZonedDateTime(Java) <=> 'timestamp' (Oracle)
Well, actually Oracle's 'date' type can also stores time and in most cases we use date rather than timestamp in Oracle, but LocalDate in Java doesn't.
Is there a way to provide ZonedDateTime(Java) <=> 'date'(Oracle) mapping? I'm modifying _added_entity.xml template to do this for now. But hope this can be resolved eventually.
Thanks!

**Comment by MathieuAA** [comment]
Hi, you should ask this question in the generator's issue tracker. Thanks.
