### ISSUE TITLE
Does jhipster-jdl support entity extending from AbstractAuditingEntity?

### ISSUE THREAD

**Issue by dancewing** [jhipster/jhipster-core#118]
AbstractAuditingEntity is good abstract class for audit, but now only User entity use it, can other entities such as generated from jdl use it ? 
from my opinion, if jdl can support "entity * with audit" like "dto * with mapstruct", entity extend from AbstractAuditingEntity when generated by jhipster:entity tool.

**Comment by MathieuAA** [comment]
Hello, a [similar issue](https://github.com/jhipster/jhipster-core/issues/24) has already been closed.
