### ISSUE TITLE
Relationship with enum JDL

### ISSUE THREAD

**Issue by Blackdread** [jhipster/jhipster-core#122]
Hi,

Why cannot we use relationships (any relationship) to Enum in JDL?

I put an example of JDL using a ManyToMany directly to the enum but this does not work.
A solution is to use an entity "MyExampleValue" that only serve as an intermediate for relationship (change MtM to "Example{values} to MyExampleValue"

`
entity Example {
    aValue String required
}

entity MyExampleValue{
    myExample MyExample required
}

enum MyExample {
    VAL_ONE,
    VAL_TWO
}

relationship ManyToMany {
    Example{values} to MyExample
}
`

**Comment by MathieuAA** [comment]
Hello, Enums can't have relationships because they aren't entities. You can wrap enumerations inside a class, and have them as types.
Your JDL would look like:

```
entity Example {
aValue String required
}

entity MyExampleValue{
myExample MyExample required
}

enum MyExample {
VAL_ONE,
VAL_TWO
}

relationship ManyToMany {
Example{values} to MyExampleValue
}
```
