### ISSUE TITLE
As a developer I want to specify packages in my JDL file

### ISSUE THREAD

**Issue by kronzucker** [jhipster/jhipster-core#123]
This is my case:
As a developer I want to specify packages for jdl generated classes.

This is necessary since we use a functional/technical naming strategy to keep classes togther.

example:
com.companyx.projecta.dataimport.rest
com.companyx.projecta.dataimport.database
com.companyx.projecta.notifications.database
com.companyx.projecta.configuration.database
com.companyx.projecta.auditing.database
com.companyx.projecta.<functional aspect>.<technical aspect [optional]>

How can this be achieved in a JDL file?

I woudl assume that I structure the JDL as following:
package dataimport {
    entity import {
           ...
    }
}
package notifications {
    entity notification { ... }
    entity notificationStrategy { ... }
    ....
}

package configuration {
     entity applicationParameter { .... }
     entity applicationParameterValue { ... }
}

**Comment by jdubois** [comment]
I'm sorry but we don't do this at the moment...

- You can move your code around with your IDE, that's quite easy
- You can use the microservice approach if you really want to split your code into modules

There has already been lots of discussion about this, and of course that can still be discussed, but that's the way it is done now.

**Comment by kronzucker** [comment]
Thanks for your feedback, although that was not what I wanted to hear :-)
