### ISSUE TITLE
Use npm-check-updates lib instead of check_dependencies.js script

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#124]
@MathieuAA checkout https://www.npmjs.com/package/npm-check-updates
I just saw the `check_dependencies.js` file and wanted to check if you considered the above plugin? I have been using it for a long time and its a good one

**Comment by MathieuAA** [comment]
@deepu105 Thanks Deepu! I'll check this out tonight!

**Comment by MathieuAA** [comment]
Closing this. Yarn does this with `yarn outdated`.

**Comment by deepu105** [comment]
nice


Thanks & Regards,
Deepu
