### ISSUE TITLE
Comments with quotes in JDL get copied in Swagger annotation

### ISSUE THREAD

**Issue by agoncal** [jhipster/jhipster-core#126]
If you take the following JDL : 

```
/**
* Ok comment
*/
entity EntityOK {
}

/**
* Comment="KO"
*/

entity EntityKO {
}
```

then you get the two Entities generated, but the code of the EntityKO will not work. This is because the comment gets copied as it is in the Swagger @ApiModel annotation (notice the double quotes around KO): 

```
@ApiModel(description = "Comment="KO"")
@Entity
@Table(name = "entity_ko")
public class EntityKO implements Serializable {

```

**Comment by MathieuAA** [comment]
@agoncal Hi, nice catch! Can you submit a PR for this? I'll fix it later today if you don't =)

**Comment by agoncal** [comment]
@MathieuAA On my way to Google Cloud training... I'll be off for the day ;o)

**Comment by MathieuAA** [comment]
@agoncal ahah roger that! I'll handle it then.

**Comment by MathieuAA** [comment]
The problem's in the generator... I'll submit a PR.
