### ISSUE TITLE
Better service support in JDL

### ISSUE THREAD

**Issue by agoncal** [jhipster/jhipster-core#127]
At the moment we can generate a service or not with a single line in the JDL :

`service Proposal with serviceClass`

It would be good to be able to add method signature to generate methods. With a simple grammar and focusing on defaults. 

```
service Proposal with serviceClass {
  method1(String),                   // public void method1(String param1)
  method2(String s),                 // public void method2(String s)
  String method3(Integer, Integer),  // public String method3(Integer param1, Integer param2)
  private MyEntity method4(Integer)  // private MyEntity method4(Integer param1)
}

```
This would create the same methods as today (save, findAll, findOne, delete) as well as creating the demanded methods.

**Comment by MathieuAA** [comment]
@agoncal for this to happen, the generator must be updated to accept this kind of input. As for the JDL (parsing, exporting, etc.), it would be easy to do.
@jdubois what do you think?

**Comment by hakandilek** [comment]
I think it would better be discussed together with jhipster/generator-jhipster#6275.

**Comment by agoncal** [comment]
Closing and referencing this issue on [Enriching the JDL grammar #6275](https://github.com/jhipster/generator-jhipster/issues/6275)
