### ISSUE TITLE
Embeddable For Value Objects

### ISSUE THREAD

**Issue by vw98075** [jhipster/jhipster-core#128]
Currently, the JDL treats all domain objects as entity objects. According to domain driven design, there is another type of domain class, value object. Is possible to add another entry, embeddable for value objects? If yes, on the "one" end of a relationship, the entry would be mapped to @Embedded and on the "many" end of a relationship, the entry would be mapped to @ElementCollection. That shall be doable.

**Comment by MathieuAA** [comment]
@vw98075 I'm not I understand, what would the "contained" type be? a String/Integer/whatever for instance?

**Comment by vw98075** [comment]
Here is a quote on the value object.

> In DDD, there are three defining characteristics of a value object:

> It has no identity key (this aligns with a complex type)

> It’s immutable

> When checking its equality to other instances of the same type, all of its values are compared

A Country object and an Address object have the above characteristics.
 
We can learn the concept from the point of JPA: @Embeddable, @Embedded and @ElementCollection although @Embeddable doesn't guarantee immutable out of the box. JDL shall allow people express their DDD freely, but not limit such expression. The current version of JDL only has one entry mapped to one of three JPA class annotations: Embeddable, Entity, and MappedSuperClass.

**Comment by MathieuAA** [comment]
The JDL has nothing to do with this. Here's the flow:
  - First the user writes JDL code,
  - It gets parsed by the parser in this project,
  - Entities are written **in JSON form** (and not in Java),
  - The generator, then, is used to create the entities (and the various Java/JS/TS files)

You must submit your request to the generator's issue tracker.

**Comment by jdubois** [comment]
Yes, and the generator doesn't go that far, and probably never will.

**Comment by vw98075** [comment]
If I make changes on a generated code base in the regard, are my changes maintainable in the space of JHipster? Are my changes going to be overwritten when I update the JHipster version?

**Comment by MathieuAA** [comment]
It's very likely, yes.

**Comment by deepu105** [comment]
@vw98075 this is what modules are for. You can add a module for this and if the module becomes popular in community we could consider merging it into main generator

**Comment by vw98075** [comment]
@MathieuAA Yes for "maintainable" or "overwritten"?

**Comment by vw98075** [comment]
@deepu105 I can look into the option. Can you point me the code which generates entity classes from a jh file?

**Comment by MathieuAA** [comment]
For overridden.

**Comment by jihlee** [comment]
Hello @vw98075, how did you deal with this issue?
I'm quite interested with this issue.
