### ISSUE TITLE
Add support for List of datatype

### ISSUE THREAD

**Issue by agoncal** [jhipster/jhipster-core#129]
It would be good to have support for lists of datatypes. For example, here I could map a proposal which has a list of tags :

```
entity Proposal {
    title String,
    tags List<String>
}
```

This could generate the following entity : 

```
@Entity 
public class Proposal {
   private String title;

   @ElementCollection
   @CollectionTable(name="tag_proposals", joinColumns=@JoinColumn(name="proposal_id"))
   @Column(name="tag")
   List<String> tags;
```

And why not allowing also sets : 

```
entity Proposal {
    title String,
    rakings Set<Integer>,
    tags List<String>
}
```

**Comment by MathieuAA** [comment]
That'd be interesting indeed! Again, all the heavy work would have to happen in the generator.
cc @jhipster/developers

**Comment by deepu105** [comment]
I also had many people asking me about this feature so I tink might be worth to add in next major version

**Comment by MathieuAA** [comment]
@agoncal I'll try some things this week-end

**Comment by hakandilek** [comment]
better to discuss together with jhipster/generator-jhipster#6275.

**Comment by agoncal** [comment]
Closing and referencing this issue on [Enriching the JDL grammar #6275](https://github.com/jhipster/generator-jhipster/issues/6275)

**Comment by delkant** [comment]
Was this feature forgotten or declined? is there any plans to have it in the future?. I can see it as part of the features described in the first post here[#6275](https://github.com/jhipster/generator-jhipster/issues/6275) but not included/explained at the end. The ticket also was closed with the tag for version 4.8 but I cannot find anything like List<String|Integer> in the documentation. Thanks.

**Comment by MathieuAA** [comment]
@delkant Searching a little bit should have made you look at [this issue](https://github.com/jhipster/jhipster-core/issues/141)

**Comment by hosseinmp76** [comment]
this issue and the referenced issue #6275 are both closed. but I don't find any discussion on this feature in #6275 either.
is this feature rejected?
