### ISSUE TITLE
Move common code to JDL

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#13]
Move some of the common code to JDL so that we can use it in JHUML and the sub generator
This would make JDL act like a parent library kind of thing for all Jhipster projects that requires these info. Another option would be to move all the common reusable code to a new project called `jhipster-core` what do you think @MathieuAA ?

This can address @MathieuAA request to have some reusable code from JHipster in a module. Though may not be the most intuitive way this could be a viable solution 
1. **database attribute types**: this can be moved from JHUML to here so that this becomes the reference point for different types used in the generator, JHUML, JDL studio and JDL and if @jdubois and @jhipster/developers are ok then I can refactor the entity sub generator to get the types from JDL while constructing the questions. only downside of this would be that if we need to add a new type we have to add it here rather than adding it directly in the generator, but then it saves us the trouble of updating all different projects to handle the new type
2. **dsl_parser**: IMO this can be moved to JDL project, it has dependency on `parser_helper `and `jhipster_option_helper` but those are minor util methods which can be either duplicated or moved to this project and referenced in JHUML since it will have JDL as a dependency anyway
3. **ClassScheduler**: with the current way of liquibase not being order dependent is this required? if so can it be moved here and referenced from JHUML 
4. **EntitiesCreator**: can this be moved here as well

**Comment by MathieuAA** [comment]
I'd make another project instead of putting code here.

**Comment by deepu105** [comment]
im fine either way

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
@deepu105 What if this module could export JHipster JSON files?

**Comment by deepu105** [comment]
@MathieuAA what do you mean. Are you talking about JDL or a new module?

**Comment by MathieuAA** [comment]
This module.
My point is:
  - It's a JHipster project,
  - It handles the JDL and everything around it (only as input, and everything else as output),
  - Dealing with JSON files from JDL is a task in its scope.

**Comment by deepu105** [comment]
yes that is what I originally asked for

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
My intention when we started the JDL as a separate project was that it can read JDL files and produce JHipster entity Json as one of the output output.
If you remember my original idea was to have the below methods
`parse` function which just gives the pegJs output, this is useful for JDL studio
`parseToEntity` function which outputs Jhipster entity json from JDL

**Comment by deepu105** [comment]
we had that discussion here https://github.com/jhipster/jhipster-domain-language/issues/1

**Comment by MathieuAA** [comment]
Yes, I remember but it seemed kind of redundant with what the subgen does. That's why I asked you ;)
Anyway, I'll try to do it this week-end.

Le 21 avril 2016 07:26:49 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>we had that discussion here
>https://github.com/jhipster/jhipster-domain-language/issues/1
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-domain-language/issues/13#issuecomment-212750390

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
If JDL does that then I would just use it and remove all that code from
subgen

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
its tracked in #28
