### ISSUE TITLE
Field Name with lowercase first letter generates incorrect code

### ISSUE THREAD

**Issue by lowlee** [jhipster/jhipster-core#130]
With the following JDL

```
entity Task {
  tEST String
}
```

the getters and setters are generated with names `gettEST()` and `settEST()` but the `toString()` method is generated with a call to a different form of the getter and the Java fails to compile.

```java
public String toString() {
  return "Task{" +
    "id=" + getId() +
    ", tEST='" + getTEST() + "'" +
    "}";
}
```

The generated code in `toString()` is correct if the field name has more than one lowercase letter at the start eg:

```
entity Task {
  anotherTEST String
}
```

generates getters and setters `getAnotherTEST()` and `setAnotherTEST()` and the correct form of the getter in `toString()`

```java
public String toString() {
  return "Task{" +
    "id=" + getId() +
    ", anotherTEST='" + getAnotherTEST() + "'" +
    "}";
}
```

**Comment by deepu105** [comment]
either duplicate or related to https://github.com/jhipster/generator-jhipster/issues/5969
