### ISSUE TITLE
Forbid constraints with no value

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#131]
Like in
```
entity Hello (hello) {
  name String minlength(5) maxlength(25),
  age Integer required min max(150)
}
```

**Comment by deepu105** [comment]
@MathieuAA I think when no values are specified we can just use the default values, same as in the generator. WDYT?

**Comment by MathieuAA** [comment]
@deepu105 I was thinking about that too, but do all the constraints have default values? I'd find it weird that the syntax be allowed only for some constraints.

**Comment by deepu105** [comment]
Not sure we need to check the prompt.js files in generator
