### ISSUE TITLE
Support for non-English characters in JDL RegEx parser

### ISSUE THREAD

**Issue by stieler-it** [jhipster/jhipster-core#139]
Writing a German application we noticed that we could not use the following regular expression for pattern validation in JDL that works in the .jhipster JSON files:

`^[A-ZÄÖÜa-zäöüß\- ]*$`

(This would be to validate a German institution name)

I tried to use hexadecimal character codes like `\xAF` which also didn't work becuase a backslash is automatically escaped.

Of course we could workaround this by changing the expression in the parser. However, just adding characters we want to use feels wrong. Can we somehow allow everything in Regexp? Maybe we should also allow to use a backslash es escape character to allow e.g. character classes like `\w`.

Any opinions?

**Comment by MathieuAA** [comment]
It's clearly something I overlooked!

**Comment by MathieuAA** [comment]
@stieler-it So, I've introduced a better way of defining a regex:
```
entity A {
  myField String pattern(/^[A-ZÄÖÜa-zä\öüß\- ]*$/)
}
```
I've gotten rid of the apostrophe separator and used the standard slash. The only issue is that one's got to write the ASCII code for the slash instead of the slash in a pattern to use it (PegJS isn't very good at everything regex-related).

**Comment by deepu105** [comment]
@MathieuAA that's sounds fine can you also document this? so that people don't raise issues on that?

**Comment by stieler-it** [comment]
@MathieuAA 

- I assume the backslash before "ö" in your example is a typo. Then, that would fix our problem with special characters. Thank you!
- Did I miss something or is it still not possible to use the backslash as escape character because it would be escaped automatically? So, is it actually possible to specify ASCII codes as you suggest?

**Comment by MathieuAA** [comment]
@stieler-it no the backslash was just a test =)
You can use backslash! That's why I suggested you use them in order to include them in any regex having forward slashes.

**Comment by stieler-it** [comment]
@MathieuAA What has to be done that the new syntax also works in [JDL Studio](http://www.jhipster.tech/jdl-studio/)?

Currently, I'm getting a `Expected ["|'] but "/" found. -> line: 4` error.

**Comment by MathieuAA** [comment]
I have yet to release it. I'll do it when I have some free time

**Comment by deepu105** [comment]
The js file reference needs to be updated in jdl studio bower file as well

**Comment by stieler-it** [comment]
@MathieuAA 
If we are using a regexp like `pattern(/^[^0-9#!"§$%&\x7F()=?\\*+~#,;\.:]*$/)` the `\x7F` appears as `\\x7F` in the .json file. It seems, for some reason, that neither `\\x7F` in Java nor `\x7F` in our Angular code seems to have an effect. Do you have an idea why?

**Comment by MathieuAA** [comment]
I'll have a look at it today but I wonder... `0x7F` looks like an hex code, so I guess that's the number for `127`.  And this code is `DEL`. What is it you're trying to achieve here? Maybe there's a workaround.

**Comment by stieler-it** [comment]
Yes, embarassing. We want to achieve a \x2F (slash). I have no clue why I tried 7F. Sorry, I'm sure it works now. Still, it's a workaround because a real slash would terminate the regular expression.

**Comment by MathieuAA** [comment]
@stieler-it don't be! I know the pattern in JDL is not that robust, and I'm looking into something to make it better.
