### ISSUE TITLE
Preserve column names when using snake-case names by JDL import

### ISSUE THREAD

**Issue by micobarac** [jhipster/jhipster-core#148]
In case of importing snake-case column names using JDL, underscores are omitted during code generation, which is a problem.

`accounting_requests_number` becomes `accountingrequestsnumber` .

**Comment by MathieuAA** [comment]
Why do you even have such names? JHipster handles that itself

**Comment by jdubois** [comment]
Yes @MathieuAA this is going to complexify the JDL, and I don't understand the added value. This is work & maintenance for you, I wouldn't spend time on this.

**Comment by MathieuAA** [comment]
@jdubois Yeah, that too.

**Comment by MathieuAA** [comment]
@micobarac if I were you, I'd just have my jdl field named as the Java convention recommends.

**Comment by micobarac** [comment]
Column names in our Cassandra database are modeled by using snake case. There's nothing I can do about it. I don't see why this would complexify the JDL.

**Comment by micobarac** [comment]
As I can see, camel case names are preserved, snake case names lose underscores during JDL import, which sucks.

**Comment by jdubois** [comment]
Oh sorry you should have said you were using Cassandra. That makes much more sense to me as you don't have Hibernate.

**Comment by micobarac** [comment]
Yep, sorry for not telling you this. Jhipster proposes using raw CQL queries and snake-case column names.
