### ISSUE TITLE
Have some kind of annotating/tagging system in the JDL

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#150]
So we don't have to do this:
```
entity A

microservice * with whatever
```

and just have 
```
microservice('whatever')
entity A
```

Note that the first syntax is really nice if you decide to add another entity: you won't have to change the option.

@agoncal A promise's a promise.

**Comment by deepu105** [comment]
@MathieuAA I proposed to have the annotation system long back :smiling_imp: 
Anyways I think below might be much easier to understand as we are very used to it in other languages
```
@microservice('whatever')
entity A
```

**Comment by deepu105** [comment]
Similar what https://github.com/hakandilek/vagabond-uml does

**Comment by deepu105** [comment]
Ping @hakandilek 
From the readme
## Annotations

Annotations are used to represent special characteristics of Entites or Entity attributes.

```java
@paginate(pagination)
entity Job {
  Long jobId
  String jobTitle
}
```
In this example `Job` entity has the `@paginate` annotation with `pagination` property.

```java
@dto(mapstruct)
entity JobHistory {
  startDate ZonedDateTime,
  endDate ZonedDateTime
}
```
In this example `@dto` annotation is applied on the `JobHistory` entity with `mapstruct` 
property.

Annotations can be combined.

```java
@dto(mapstruct)
@paginate(infinite-scroll)
entity Employee {
  Long employeeId 
  String fullName
}
```
In this example `@dto` and `@paginate` annotations are applied together on the 
`Employee` entity.

**Comment by MathieuAA** [comment]
@deepu105 that was an intended surprise :)

**Comment by hakandilek** [comment]
@deepu105 thanks for the ping. Well, the syntax is not complete, let's share ideas to bring it forward. :-)

**Comment by cbornet** [comment]
What would be the syntax for `*` and `except` ?

**Comment by deepu105** [comment]
This would be additional syntax to existing so * & except should work in
old syntax and they dont make sense in a single entity annotation anyway


Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
Closing this one in favor of the new issue which will developed right after the migration to chevrotain.
