### ISSUE TITLE
representing Lists/Arrays in JDL

### ISSUE THREAD

**Issue by sulmansarwar** [jhipster/jhipster-core#156]
There needs to be a way to represent Lists and Arrays in JDL. Example:

```
entity Student{
id String required,
surName String,
firstName String,
dateOfBirth Date,
rank RANK,
function Function,
studentStatus StudentStatus,
absences Absenses[],
}

```

In this example, 'absences' is a list of Absences. How do we represent a List of objects? I did not find any example or mention in the docs.

**Comment by sulmansarwar** [comment]
Can we do 
absences List<Absence>
?

**Comment by deepu105** [comment]
This is not the right place for this. JDL can support this only if the generator supports it and at the moment we dont have any plans to do this.
