### ISSUE TITLE
SQL & MongoDB field types & validation

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-core#163]
For JDL and core code, SQL databases and MongoDB have two different definitions of field types and validation rules (see https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/field_types.js#L46).

But in Generator JHipster, both SQL databases and MongoDB have same list of fields and rules (see https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L480).

Is there a reason for separating these rules?

I'm currently writing a PR for integrating Couchbase in JDL (Couchbase is not supported in JDL yet) and I'm wondering if I can merge MongoDB+Couchbase or SQL+MongoDB+Couchbase or if I have to create a third identical block for Couchbase.

Thanks.

**Comment by MathieuAA** [comment]
Hi, if one day we support one more field type for MongoDB, when we'd just have to add it without separating. Now, that was the initial idea. However, since definitions haven't been different for at least two years, I guess we can merge them!
Thanks!

**Comment by hdurix** [comment]
Ok thanks let's merge them then. I'll do it in my PR.

**Comment by hdurix** [comment]
@MathieuAA I have something I don't understand with the current master branches from jhipster-core and generator-jhipster for the JDL file import.

In the generator, the call for JDL import is given with 4 arguments:
https://github.com/jhipster/generator-jhipster/blob/master/generators/import-jdl/index.js#L89

The function binding seems to be there:
https://github.com/jhipster/jhipster-core/blob/8b580598faeb50b31f18431c60398493ff361dd6/module/index.js#L65

Then, the signature of the core function shows it only accept one argument now:
https://github.com/jhipster/jhipster-core/blob/master/lib/parser/jdl_parser.js#L34

So when I try to run the current JDL import from generator, it is failing.

Do I miss something here? Or does a PR need to be done in the generator? Do you use this piece of code in an other project?

**Comment by MathieuAA** [comment]
Hi, the generator uses v1.3.7 (not master) of this project (I may have slightly fucked up the branching...). The branch is `dev`.

**Comment by hdurix** [comment]
Oh okay thanks that's what I was missing!

So for testing the generator JDL import, I have to create a branch from v1.3.7 instead of master. I'll test that.

**Comment by MathieuAA** [comment]
You can fork the dev branch, the master branch will be v2.0.0 (and everything will be there eventually)

**Comment by hdurix** [comment]
Ok I'll do the PR from the dev branch
