### ISSUE TITLE
Clean up unary option declaration

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#165]
There shouldn't be two different syntaxes when declaring them.
The `for` keyword should be removed.
From [there](https://github.com/jhipster/generator-jhipster/issues/6286)

**Comment by MathieuAA** [comment]
Yet to be released

**Comment by colameo** [comment]
@MathieuAA when is it supposed to release this change? We could also make the "for" keyword optional as this is a breaking change for existing projects.

**Comment by MathieuAA** [comment]
@colameo Hi, yeah I know and sorry about that. It was already released (v1.4.0)
