### ISSUE TITLE
Addition to JHipster help: integration with Sparx EA UML models

### ISSUE THREAD

**Issue by guillaumefinance** [jhipster/jhipster-core#166]
Hi,

I defined last year an integration module to generate JDL content from UML model defined in Sparx Enterprise Architect tool.
This module (Sparx MDG) has been used by our dev team to create Entities in JHipster from UML class diagrams created in Sparx EA.

I published this week an Open Source project in Github so it can contribute towards the community and let anyone improve it with the latest JHipster features (this MDG supports definitions for JHipster 2.

If that's possible, I would like to provide a help page on this module within JHipster help, as a new page or to be added in http://www.jhipster.tech/jhipster-uml/ 

The Github project ref is //github.com/guillaumefinance/MDG-Sparx-EA-UML-JHipster
An associated article is available here: http://www.umlchannel.com/fr/enterprise-architect/item/203-mdg-viseo-ea-uml-to-jhipster-generator-generateur-entites-jdl-jhipster-modeles-uml-sparx-enterprise-architect

What do you think? I contacted Julien Dubois who liked the idea and suggested I should create an issue here.

Thanks,
Guillaume

**Comment by MathieuAA** [comment]
Hello Guillaume! 
The JUML project can already export JDL from UML files, but not with this editor, because it's not free and we can't offer any support for it. The fact that you've done it, with JDL export, is pretty awesome!
If you plan on keeping your repo up and updated, we can create an entry in the doc (under the JHipster UML section) so that your repo is directly visible from there. Plus, I can update the README in the JUML project to point to your repo.
What do you think?

**Comment by guillaumefinance** [comment]
Hi Mathieu,
Sounds good to me. Please let me know when the doc is updated so that I can add a link from my project.
Thanks.

**Comment by MathieuAA** [comment]
Sorry for the lack of update, I was pretty busy. I'll make a PR tonight and update our projects to make it happen.

**Comment by MathieuAA** [comment]
Oh by the way, do you have an english copy of the [doc](http://www.umlchannel.com/fr/enterprise-architect/item/203-mdg-viseo-ea-uml-to-jhipster-generator-generateur-entites-jdl-jhipster-modeles-uml-sparx-enterprise-architect)? It would be great

**Comment by guillaumefinance** [comment]
Hi, 
The english doc is [available here](http://www.umlchannel.com/en/enterprise-architect/item/204-mdg-viseo-ea-uml-to-jhipster-generator-jdl-uml-model-sparx-enterprise-architect).

Thanks

**Comment by MathieuAA** [comment]
Awesome, thanks!!

**Comment by MathieuAA** [comment]
Julien has merged the update. I'm closing this issue, don't hesitate to add anything here!

**Comment by guillaumefinance** [comment]
Thanks Mathieu. 
I noticed a minor issue with the anchor link from the summary to Other Editors.
It should be http://www.jhipster.tech/jhipster-uml/#-other-editors instead of http://www.jhipster.tech/jhipster-uml/#othereditors

**Comment by MathieuAA** [comment]
Thanks, can you make a PR?
