### ISSUE TITLE
Being able to generate enums that are not related to an Entity

### ISSUE THREAD

**Issue by agoncal** [jhipster/jhipster-core#167]
##### **Overview of the issue**

JDL is able to generate an enum that is used by an entity, but ignores any enum that has no relation.

##### **Motivation for or Use Case**

Most of the time, enums are related to Entities, but some can be used only by services. It would be good to have JHipster generating them too.

##### **Reproduce the error**

Take a simple JDL file. The entity `Contract` has an enum `ContractType`. Both, the entity and the enum are genreated by JHipster. On the other hand, `Metadata` is an enum that has no relation to any entity, but will be used by a service. `Metadata` is ignored and JHipster does not generate anything. It would be good if it could.

```
entity Contract {
    price Integer,
    discountRate Float,
    vatRate Float,
    contractType ContractType
}

enum ContractType {
    SPONSOR_AGREEMENT, INVOICE
}

enum Metadata {
    TENANT, EVENT, SPONSOR
}
```

##### **JHipster Version(s)**

```
noenum@0.0.0 /Users/agoncal/Documents/Code/Quantixx/temp/noenum
└── generator-jhipster@4.10.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.quantixx.sponsor"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "noenum",
    "packageName": "io.quantixx.sponsor",
    "packageFolder": "io/quantixx/sponsor",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Contract (contract) {
  price Integer,
  discountRate Float,
  vatRate Float,
  contractType ContractType
}

enum ContractType {
  SPONSOR_AGREEMENT,
  INVOICE
}

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.14.2

node: v8.7.0

npm: 5.4.2

bower: 1.8.0

gulp:
[14:39:23] CLI version 1.3.0

yeoman: 2.0.0

yarn: 1.2.1

Docker version 17.10.0-ce, build f4ffd25

docker-compose version 1.17.0-rc1, build a0f95af

**Comment by MathieuAA** [comment]
I didn't know that, that's a bug. I'll check it.

**Comment by cbornet** [comment]
No it's not a bug. JHipster currently only generate enums that are associated to an entity.

**Comment by MathieuAA** [comment]
@cbornet thanks for the clarification... What about Antonio's use case though? It stands.

**Comment by gmarziou** [comment]
Unless I'm wrong,  the only code that JHipster would generate in this case is the java enum, so it seems to me it would go against [policy #2](http://www.jhipster.tech/policies/).

**Comment by MathieuAA** [comment]
@gmarziou Hi! Even though the use case is somewhat valid from a generation viewpoint (a bit stretched though I admit as we dont _yet_ generate services from scratch), I guess you're right.

**Comment by agoncal** [comment]
What about adding this to [Enriching the JDL grammar](https://github.com/jhipster/jhipster-core/issues/141) ?

**Comment by deepu105** [comment]
The problem is if its added in grammer it needs to be implemented in the
generator as well. And as @gmarziou said creating enums really doesn't have
any value as it will be exactly same code you write in jdl put inside a
java file. But we would have to write a lot if code to do that which seems
overkill

**Comment by agoncal** [comment]
I understand. The idea behind enriching the grammar, being able to generate repository methods, enums.... is to have the JDL being the spine of an application. Again, that could be specific to us, but once the JHipster code is generated, we do not change it, we only add extra classes. So, for us, the more JHipster can do, the better.

Closing this issue... but referencing it from https://github.com/jhipster/jhipster-core/issues/141 ;o)

**Comment by asjrosabal** [comment]
Hello, I would like to know how I can to create a complex enum in jdl studio? Something like this:

public enum Equipo
{
	BARÇA("FC Barcelona",1), REAL_MADRID("Real Madrid",2),
	SEVILLA("Sevilla FC",4), VILLAREAL("Villareal",7); 
	
	private String nombreClub;
	private int puestoLiga;
	
	private Equipo (String nombreClub, int puestoLiga){
		this.nombreClub = nombreClub;
		this.puestoLiga = puestoLiga;
	}

	public String getNombreClub() {
		return nombreClub;
	}

	public int getPuestoLiga() {
		return puestoLiga;
	}	
}

Thanks

**Comment by deepu105** [comment]
@asjrosabal for the moment you cant. Its not supported
