### ISSUE TITLE
Documentation inconsistencies

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#168]
The docs at http://www.jhipster.tech/jdl/ seems to be a bit inconsistent at some places
For example 
1. below code is wrong as the min/max is not applicable to String and field type is missing
```
entity A {
  myString required min(1) max(42) pattern(/[A-Z]+/)
}
```
2. required validation for relationship is not clear
3. search or searchEngine as both are mentioned, also this option is not clearly documented

@MathieuAA I found few of these could you take a look at the page when you have time and see if there is any other issue, I can update them if you don't have the time

**Comment by MathieuAA** [comment]
Thanks @deepu105 !! I'll have a look this afternoon or tonight!

**Comment by MathieuAA** [comment]
@deepu105 thanks again ;)
