### ISSUE TITLE
Filtering does not work in the JDL because there's no default service value

### ISSUE THREAD

**Issue by duderoot** [jhipster/jhipster-core#169]
When using filter in a JDL file the generated json files in .jhipster folder have only `jpaMetamodelFiltering: true`. According to the [documentation](http://www.jhipster.tech/entities-filtering/)  the json files need also to have a different value then **no** for `service` e.q. `service: "serviceClass"`
##### **Reproduce the error**
[Here](https://github.com/duderoot/jhipster6735/commit/bdbe74339a6dcc471f5666804bea8219163bb17b) I created an application with the latest jhipster cli from master.
##### **Related issues**
[#6735](https://github.com/jhipster/generator-jhipster/issues/6735#issuecomment-348706532) from jhipster-generator is in somehow related to this

##### **Suggest a Fix**

- update the documentation and specify that _service_ is required for option  _filter_
- when filter is used in JDL file then create a default value for service like `service: "serviceClass"`
I can do a PR I just want to hear other opinions.

**Comment by MathieuAA** [comment]
All in all, this is just about issuing a warning and setting values when the user wants to filter. I'll do it.
