### ISSUE TITLE
Import multiple JDL model files into another one ?

### ISSUE THREAD

**Issue by cvgaviao** [jhipster/jhipster-core#170]
I'm working on a model that is becoming a bit bigger. 
Would be possible to split that model into many files and then "import" then into others?

**Comment by MathieuAA** [comment]
Here, read [this](http://www.jhipster.tech/jdl/#howtojdl)

**Comment by cvgaviao** [comment]
@MathieuAA , thanks !
Nice to have the possibility to use multiple jdl files while generating code. ? :) 
But what I'm missing is the possibility to "crtl-space" while creating relationships in the  Eclipse editor and to refer to entities that was created in another file.

**Comment by MathieuAA** [comment]
This isn't the project for this. Check the JHipster-IDE project for that
