### ISSUE TITLE
 How to skim the resources and repository generation ??

### ISSUE THREAD

**Issue by julianotorquato** [jhipster/jhipster-core#172]
### The issue

---

### Motivation for or Use Case

---

### Reproduce the error

---

### Related issues

---

### Suggest a Fix

---

### The JDL file

---

### Versions 

| JHipster           |
| ------------------ |
| `JHipster Version` |

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Please follow our issue template and guidelines. Currently its not possible to skip these, just remive the files yiu don't want manually
