### ISSUE TITLE
Export JDL exports wrong pattern for regex

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#173]
### The issue

`email String required pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)` is exported as 
`email String required pattern(^[^@\s]+@[^@\s]+\.[^@\s]+$),` and hence resulting JDL becomes invalid.

### Versions 

| JHipster           | master
| ------------------ |
| `master` | 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@MathieuAA would you able to take a look my hands are quite full

**Comment by MathieuAA** [comment]
@deepu105 I'll have a look tomorrow!

**Comment by deepu105** [comment]
Thanks man

On 16 Jan 2018 10:50 pm, "Mathieu ABOU-AICHI" <notifications@github.com>
wrote:

Closed #173 <https://github.com/jhipster/jhipster-core/issues/173> via
0ef7521
<https://github.com/jhipster/jhipster-core/commit/0ef752169fdef8cb53e0b7ef63d42ec1978b41d5>
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/jhipster-core/issues/173#event-1427115613>,
or mute
the thread
