### ISSUE TITLE
Import of Microservice Entity Fails

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#176]
### The issue
Importing the following JDL in its microservice results in an error:

```
entity A {
    name String
}
microservice A with ms
```
```
$ jhipster import-jdl test.jdl
TypeError: Cannot set property 'microserviceName' of undefined
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! 
Error while parsing entities from JDL

    at Environment.error (/Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/Users/ruddell/Dev/Contrib/generator-jhipster/generators/generator-base.js:2030:18)
    at module.exports.parseJDL (/Users/ruddell/Dev/Contrib/generator-jhipster/generators/import-jdl/index.js:116:26)
    at Object.<anonymous> (/Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/lib/index.js:399:25)
    at /Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/ruddell/Dev/Contrib/generator-jhipster/node_modules/yeoman-generator/lib/index.js:400:11)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)

```

### Suggest a fix
The method causing issues is `setEntityNamesOptions` in [entity_parser.js](https://github.com/jhipster/jhipster-core/blob/master/lib/parser/entity_parser.js#L141).  It attempts to set the microserviceName for a `*` entity which does not exist as a key in the `entities` object.

### Reproduce the error

Generate a microservice with the `ms` basename and import the above JDL.  Config provided below.

### Related issues
https://github.com/jhipster/generator-jhipster/issues/7015
https://github.com/jhipster/generator-jhipster/issues/6712
### Suggest a Fix

Not sure

### The JDL file
```
entity A {
    name String
}
microservice A with ms
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.3",
    "baseName": "ms",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

### Versions 

| JHipster           |
| ------------------ |
| `v4.13.3` |

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
I'll have a look

**Comment by MathieuAA** [comment]
I couldn't reproduce it... in the JCore project using a custom test suite:
```javascript
/* eslint-disable no-unused-expressions,mocha/no-exclusive-tests */
const expect = require('chai').expect;
const parseFromFiles = require('../../../lib/reader/jdl_reader').parseFromFiles;
const EntityParser = require('../../../lib/parser/entity_parser');
const JDLParser = require('../../../lib/parser/jdl_parser');


describe.only('176', () => {
  let content = null;

  before(() => {
    const input = parseFromFiles(['./test/spec/debug/debug.jdl']);
    content = EntityParser.parse({
      jdlObject: JDLParser.parse(input, 'mysql'),
      databaseType: 'mysql'
    });
  });

  it('works', () => {
    expect(content).not.to.be.null;
  });
});
```
and by creating an application from your `.yo-rc.json` file and importing the JDL file. Did I miss something here?

**Comment by ruddell** [comment]
Here's a failing test, [it's this section](https://github.com/jhipster/generator-jhipster/blob/master/generators/import-jdl/index.js#L89-L99) of the `parseJDL` method from the `import-jdl` subgenerator.
```javascript
/* eslint-disable no-unused-expressions,mocha/no-exclusive-tests */
const expect = require('chai').expect;
const parseFromFiles = require('../../../lib/reader/jdl_reader').parseFromFiles;
const EntityParser = require('../../../lib/parser/entity_parser');
const JDLParser = require('../../../lib/parser/jdl_parser');

describe.only('176', () => {
  let content = null;

  before(() => {
    this.prodDatabaseType = 'mysql';
    this.applicationType = 'microservice';
    this.baseName = 'ms';
    this.jdlFiles = ['./test/spec/debug/debug.jdl'];

    const jdlObject = JDLParser.parse(
      parseFromFiles(this.jdlFiles),
      this.prodDatabaseType,
      this.applicationType,
      this.baseName
    );
    content = EntityParser.parse({
      jdlObject,
      databaseType: 'mysql',
      applicationType: 'microservice'
    });
  });

  it('works', () => {
    expect(content).not.to.be.null;
  });
});

```

**Comment by sendilkumarn** [comment]
There is a similar issue when using enum with microservices.

**Comment by MathieuAA** [comment]
Thanks, I'm on it

**Comment by MathieuAA** [comment]
I still can't reproduce... this is kinda frustrating as this looks like a big issue.
My tests:
  - Having a folder named `ms`, with a jhipster microservice app inside, with the same `.yo-rc.json` file, the same JDL, same jhipster version
  - Having a folder named `msdos` (I won't apologize for the joke, it was too tempting), with the same setup
  - Having enums (and not having them) in the JDL

I may have missed something here, but this is crazy

**Comment by ruddell** [comment]
@MathieuAA Does the test in my last message pass for you?  From what I see the issue only happens when the `baseName` in the .yo-rc.json matches the `microservice` specified in the JDL.
```bash
# in a new folder

# this yo-rc.json file has a matching baseName and fails
echo '{ "generator-jhipster": { "promptValues": { "packageName": "com.mycompany.myapp", "nativeLanguage": "en" }, "jhipsterVersion": "4.13.3", "baseName": "ms",       "packageName": "com.mycompany.myapp", "packageFolder": "com/mycompany/myapp", "serverPort": "8081", "authenticationType": "jwt", "cacheProvider": "hazelcast", "enableHibernateCache": true, "websocket": false, "databaseType": "sql", "devDatabaseType": "h2Disk", "prodDatabaseType": "mysql", "searchEngine": false, "messageBroker": false, "serviceDiscoveryType": "eureka", "buildTool": "maven", "enableSocialSignIn": false, "enableSwaggerCodegen": false, "jwtSecretKey": "replaced-by-jhipster-info", "enableTranslation": true, "applicationType": "microservice", "testFrameworks": [], "jhiPrefix": "jhi", "nativeLanguage": "en", "languages": [ "en" ], "clientPackageManager": "yarn", "skipClient": true, "skipUserManagement": true } }' > .yo-rc.json

# this yo-rc.json file has a different baseName and the entity generates without issue (even though it doesn't belong to this microservice)
#echo '{ "generator-jhipster": { "promptValues": { "packageName": "com.mycompany.myapp", "nativeLanguage": "en" }, "jhipsterVersion": "4.13.3", "baseName": "jhipster", "packageName": "com.mycompany.myapp", "packageFolder": "com/mycompany/myapp", "serverPort": "8081", "authenticationType": "jwt", "cacheProvider": "hazelcast", "enableHibernateCache": true, "websocket": false, "databaseType": "sql", "devDatabaseType": "h2Disk", "prodDatabaseType": "mysql", "searchEngine": false, "messageBroker": false, "serviceDiscoveryType": "eureka", "buildTool": "maven", "enableSocialSignIn": false, "enableSwaggerCodegen": false, "jwtSecretKey": "replaced-by-jhipster-info", "enableTranslation": true, "applicationType": "microservice", "testFrameworks": [], "jhiPrefix": "jhi", "nativeLanguage": "en", "languages": [ "en" ], "clientPackageManager": "yarn", "skipClient": true, "skipUserManagement": true } }' > .yo-rc.json

# generate the project
jhipster

# write the JDL to a file
echo 'entity A { name String } microservice A with ms' > test.jdl

# import the JDL
jhipster import-jdl test.jdl --force
```
I verified this with the jhipster docker image so it's definitely reproducible.
```bash
# running the jhipster image which contains the latest version pre-installed
docker run --name jhipster -td jhipster/jhipster
docker container exec -it jhipster bash 

# run the commands from the previous code section
```

**Comment by MathieuAA** [comment]
Ah! Now it fails, good!

**Comment by MathieuAA** [comment]
It works when using `*` or `all`, that's one good bug :)

**Comment by MathieuAA** [comment]
Okay, got it. Fixing it now and releasing right after. Thanks @ruddell and @sendilkumarn (I've yet to reproduce yours by the way, but I think it's the same, enums being field types...).

**Comment by MathieuAA** [comment]
Some background for the fix:
  - If a JDL with the microservice option is being imported inside a microservice project, every non-excluded entities will be imported if those entities are setup for this option (this is the normal behavior, nothing fancy here)
  - If a JDL **without the microservice option** is being imported inside a microservice project, **every entity will be imported**. See the end of #106

Now, we had this bug because I didn't respect the contract (I typed `entities` instead of `entityNames`, which is just plain stupid... my bad). The microservice option was created **without** any entity (should have used the right key in my object), and the default behavior being of the second case... that's why the entity had in its JSON `microservice: ms`.
