### ISSUE TITLE
Upgrade problem due to new reserved keyword Result

### ISSUE THREAD

**Issue by krusche** [jhipster/jhipster-core#177]
We have a big problem in our application ArTEMiS (github.com/ls1intum/ArTEMiS) due to a new reserved keyword in jhipster 'Result'

We use an entity called 'Result' in all over the places and cannot upgrade now to the newest jhipster version.

I don't see an option to rename the existing entity and it seems that the jhipster upgrade command has to generate the old code in the jhipster_upgrade branch.

Is there any way to workaround this issue?

**Comment by gmarziou** [comment]
Sorry for the inconvenience but I just saw that you committed the upgrade, so I suppose this issue can be closed.

**Comment by krusche** [comment]
I made a little hack/workaround. I started the update script, paused it in the right moment (after the jhipster core dependencies have been downloaded), then changed the file 'reserved_keywords.js' and remove the 'RESULT' entry in line 49. Then I resumed the script and it did not complain any more ;-)

The problem is, I have to do that now for every jhipster upgrade, so I wonder is it really necessary to forbid this word?

**Comment by gmarziou** [comment]
Sorry for the inconvenience but the generated java code could not compile and the typescript code was wrong., so I imagine that you made manual changes to generated code in first place.

I guess you have 2 options:

- rename the entity but keep the table name so that you don't need to migrate your database.
- agree to not upgrade anymore which should not be a big deal because JHipster 5 will be out this Spring and Angular 1 will be removed.

**Comment by krusche** [comment]
we had exactly the same issues as mentioned in https://github.com/jhipster/generator-jhipster/issues/6985 in the Java code, but simply renamed the corresponding variables. I think it might be easier to rename these results variables in the generated code instead of reserve too many keywords...

How would renaming actually work? Is there a rename command?

We currently try to migrate to Angular 5, but it is really difficult as we have a lot of legacy code :-(
We try to get some kind of hybrid mode running to be able to write new TS code in Angular5, but still to reuse the existing JS code in Angular 1.

**Comment by gmarziou** [comment]
Well maybe you could submit a pull request for a better fix that does not use a reserved keyword.

There's no rename command, you would re-generate and use your IDE to refactor.

**Comment by gmarziou** [comment]
As a side note, looking at your repo, I'd recommend that you commit your bower_components folder because bower itself advises to move to npm and so it is quite possible that some of your deps could disappear and break your app build unless you have a caching proxy.
