### ISSUE TITLE
Same jdl for multiple microservices

### ISSUE THREAD

**Issue by erreur404** [jhipster/jhipster-core#180]
Hello,

### The issue
I have two microservices sharing the same JDL like in the documentation

> entity A
entity B
entity C
microservice * with mysuperjhipsterapp except C
microservice C with myotherjhipsterapp

when I generate the entities on the microservice side (jhipster import-jdl ../jhipster-jdl.jh), all the entities are generated in both services (there are repositories and services for each entity). I have a store microservice with the Store and the Product entities, and a client microservice with the Client and Location entities. I can generate all entitites in the gateway from the store microservice. However, when Client's frontend is generated from the store microservice, its client.service.ts:resourceUrl points to client/api/client. So far, it kind of works like what I expected : Clients and Locations are saved in the client service and Store and Products are save in the store service... 

---

### Motivation for or Use Case

but when I manually change the resourceUrl to store/api/client, I can save clients too !
I think this is a bug, because I shouldn't be able to save entities in the wrong service.

---

### Reproduce the error

generate one UAA server named uaa
generate a gateway
download the JHipster registry
generate two microservices like
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "client",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "f35173b98ef864e32c8d86d3e35e322e972a6bfa",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
add the following jdl file in both microservice (jhipster import-jdl ../jhipster-jdl.jh)
...
/!\now you can already see that both service have the stuff to save entities from the other service/!\
add entities to the gateway
change for instance in src/main/webapp/app/entities/product/product.service.ts
private resourceUrl = SERVER_API_URL + 'store/api/product';
=>
private resourceUrl = SERVER_API_URL + 'client/api/product';
then launch everything and log in as admin
click entities
click product
create a new product
/!\now you can see it's being created in the wrong service/!\

---

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.14.0",
    "baseName": "client",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity Client (client)
entity Location (location)
entity Store (store)
entity Product (product) {
  name String
}

relationship OneToMany {
  Location{clients} to Client{location},
  Store{products} to Product{store}
}

service Client, Location, Store, Product with serviceClass
microservice Client, Location with client
filter Client, Location, Store, Product
microservice Store, Product with store
```

---

### Related issues

eventually issue #106 

---

### Suggest a Fix

I have no idea how to fix this, but I suppose that if the import-jdl command on the microservice side had only generated the repositories for the entities of the service, it would have been impossible to save Clients in the store microservice.
Also, I searched into the jhipster/jhipster-core/test/test_files for a test file that tests the doc exemple : 
> entity A
entity B
entity C
microservice * with mysuperjhipsterapp except C
microservice C with myotherjhipsterapp

and found that no test addresses the case of having two (or more) microservices serving different entities.

---

### The JDL file

jhipster-jdl.jh :
`
entity Client {
}
entity Location {
}
relationship ManyToOne {
	Client {location} to Location{clients}
}
entity Store {
}
entity Product {
	name String
}
relationship OneToMany {
	Store {products} to Product
}
microservice Client, Location with client
microservice Store, Product with store
filter all
`

---

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.2.windows.1

node: v8.9.2

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.4.0

Congratulations, JHipster execution is complete!

### Versions 
| `JHipster Version` |
| ------------------ |
| JHipster     4.14    |

If you have an idea of how to fix it but don't have time for it, I'd gladly give it a try but I have now absolutly no idea where to start...

Thank you for your time,

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
The best way to find out is to compare the generated JSON files. I'll do it tonight.

**Comment by MathieuAA** [comment]
I don't think this issue comes from here. I'm going to confirm it, but I'm almost 100% sure.

**Comment by MathieuAA** [comment]
Okay, my bad!! the JSON files were generated in the microservices.... even if it wasn't _their_ microservice. I'm going to fix it.

**Comment by MathieuAA** [comment]
I'm tagging this one as 'enhancement' as this isn't really a bug as the JDL is well written and should have been split in two files to be imported separately. Anyway, expect this fix very soon.

**Comment by MathieuAA** [comment]
If you want a quick fix, just exclude the entities you don't want in the other microservice.

**Comment by erreur404** [comment]
Well it wasn't bugging in normal use cases, the gateway's entity services was pointing to the right microservices so it was kind of safe. However when calling the api one could save clients in the store and products in the client ^^
When you say "exclude the entities" you mean something like
`
microservice Client, Location with client except Store, Product 
microservice Store, Product with store except Client, Location
`
?

**Comment by MathieuAA** [comment]
Yes

**Comment by erreur404** [comment]
Hello @MathieuAA ,
I tried it again, and all entities.json were generated in both microservices, even when using "except"

```
microservice Client, Location with client except Store, Product
microservice Store, Product with store except Client, Location
```

Two other points came to my mind in the weekend: 

This "except" synthax shouldn't be mandatory when someone provides the exhaustive list of entities to 'microservice', because it does not scale well with more that 2 microservices : 

```
entity A
entity B
entity C
entity D
entity E
entity F

microservice A, B with app1 except C, D, E, F
microservice C, D with app2 except A, B, E, F
microservice E, F with app2 except A, B, C, D
```

Also, my interpretation of the documentation of this function is that the "except" is here to exclude a few entities when me want to use the wilde card * or all.

The second point is that it would be really awesome that we could write only one JDL, which would tell the gateway where to find the entities and tell the microservices what to generate. 😄 

Thank you again for your time

**Comment by MathieuAA** [comment]
I've tested the exclusions, it worked. You could also have more than one JDL file (and thus split the declaration).
The fix isn't yet in master (in the generator), that's why you can't see it.
I've modified the behavior to suit what you described.
