### ISSUE TITLE
Grammar Quirks

### ISSUE THREAD

**Issue by bd82** [jhipster/jhipster-core#184]
I have some time to invest in the JDL grammar and thought to document all the syntax quirks I detect.

**Comment by bd82** [comment]
## Whitespace Sensitivity
Whitespace sensitivity bloats the grammar due to the hundreds of locations the white space rules must be handled. It is also an opening to inconsistent behaviors e.g:
* Some rules specify exactly one WS character instead of using "space+"
* Some rules use "SPACE_WITHOUT_NEWLINE" between certain elements.

### Suggestion
Make the grammar whitespace insensitive and thus allowing whitespace to be skipped completly during the lexing phase.

### backward compatibility implications
Generally a WS insensitive grammar is more general (a superset).
So it should be fully backward compatible, however, there could sometimes be edge cases where whitespace specific rules are used to disambiguate options.

**Comment by MathieuAA** [comment]
I think they won't be relevant as chevrotain brings more flexibility.

**Comment by bd82** [comment]
> I think they won't be relevant as chevrotain brings more flexibility.

I think you are correct, I am listing the things I'd like to improve as I'm first trying to reach grammar alignment and only then fix these quirks. Because some quirks fixes may cause backward compatibility changes.

**Comment by bd82** [comment]
## Comments Handling
Comments are only allowed in specific positions in the grammar.
This can be confusing to end users due to the inconsistency

### Suggestion
* Collect all comments during the lexing stage
* during parsing completely ignore comments
* after parsing attach relevant comments to the AST.

This is similar to the comment handling logic in Babylon.

### Backward Compatibility Implications
Like whitespace handling this will create a superset of the grammar so it is generally safe.

**Comment by bd82** [comment]
## Names in entityList can contain a dash ('-')

Including a dash in an identifier could conflict with future addition of an expression language.
* is 'a-b' a single identifier or a subtraction expression with two identifiers (a  -  b).

It could also cause a conflict when an integer immediately follows an identifier.
* 'a-1' vs 'a  -1' 

### Suggestion
Consider the possibility of removing this syntax.

### Backward Compatibility Implications
This would be a **breaking change**
If identifiers with dashes are  really required in entityList, the grammar could be changed
to also accept a string instead of an identifier at that location:
```
// "test-root" is wrapped in double quotes
clientRootFolder * with "test-root" except C
```

**Comment by bd82** [comment]
## FreeStyle Token in Application path config

See here: https://github.com/jhipster/jhipster-core/blob/6f503c65f0446623ac04bd3142beb9e1463227d6/lib/dsl/grammar.txt#L164

The token following a PATH token can be anything except a newline.
This is problematic because:

* As mentioned earlier this is a type of whitespace sensitivity which can lead to inconsistent behavior.
   ```
    application {
      config {
        /* A config with two properties */
        baseName toto  path ./foo/bar.java
      }
   }

    application {
      config {
        /* A config with only one property - the baseName got "swallowed" */
        path ./foo/bar.java  baseName toto 
      }
   }
   ```

* This would also be difficult to migrate to Chevrotain as it conflicts with the concept of a **distinct** lexing phase.

### Suggestion

Wrap the freeStyle token with clear delimiters, e.g:
```
    application {
      config {
        baseName toto  
        path "./foo/bar.java"
      }
   }
```

### Backward Compatibility Implications
None if this gets resolved before the application generation gets released. 😄

**Comment by bd82** [comment]
@MathieuAA Please take a look at the above comment on "FreeStyle" Token
It may be best to resolve it before it is ever released.

**Comment by MathieuAA** [comment]
Let me think about it. There's another solution, using `,`.

**Comment by MathieuAA** [comment]
I'll update the grammar tonight, thanks :)

**Comment by bd82** [comment]
Commas are also good, but would conflict with the languages configuration property.
Using Commas would avoid the ambiguity with newlines BUT there would still be a free style token
that just won't work well with a distinct lexing stage as in Chevrotain.

Have a look at the **WIP** on Chevrotain Application Generation syntax.
https://github.com/jhipster/jhipster-core/pull/183/files#diff-8761393d757a4ca7dc253978da9a7feaR391

Basically the configuration appears to be a set of key:value pairs.
Very similar to JSON, so instead of writing ALL possible pairs combinations
You can define a more general syntax of key:value pairs. (Think YAML/JSON).

And only later (after parsing) verify that the value types match the expected type for the key.
For example, that "SKIP_CLIENT" was a boolean value.

The major advantage to a more generic syntax is that it can be "expanded" without syntax changes.
So new configuration keys would **not** require changes to the grammar.
This could be even more relevant if(???) JDL has a concept of "extensions" and use cases
beyond the default "native" ones.

**Comment by MathieuAA** [comment]
Making the grammar dumber is coming after v2. I don't want to do it right now, every though it's a prerequisite to migrating to chevrotain

**Comment by MathieuAA** [comment]
I don't get the issue with commas.

**Comment by bd82** [comment]
> Making the grammar dumber is coming after v2. I don't want to do it right now, every though it's a prerequisite to migrating to chevrotain

If you do not mind small **breaking changes** in the next version then no worries. 😄 
I'm trying to separate the "grammar cleanup" and grammar migration. So I'm trying to build the grammar
to be the **most compatible** at first **including** the quirks. But I don't think the freeStyle token can be migrated in any sane manner.

**Comment by bd82** [comment]
> I don't get the issue with commas.

* Language config allows comma:
``` LANGUAGES SPACE* languages:[a-z, ]+ SPACE* applicationConfigDecl:applicationConfigDecl ```

* Config properties now use commas as optional separators.
   ```/ ',' SPACE* applicationConfigDecl:applicationConfigDecl```

So what happens when we input the following:

- ```
    application {
      config {
        // In this case the languages would be "en, fr," - An extra comma
        languages en, fr,
        baseName  toto
      }
   }
  ```
- 
   ```
    application {
      config {
        // In this case the languages would be "en, fr, baseName  toto"  - "swallowed" next property property
        languages en, fr, baseName  toto
      }
   }
``

These edge cases exist because a PEG grammar is actually more powerful as it can use parser context 
for the lexing rules. But imho this power is a **double-edged sword** because it is so easy to create these strange situations.

The standard way to fix this is create delimiters for the list of languages:
- ```
    application {
      config {
        // everything works because we can distinguish between the inner comma and the outer comma
        languages [en, fr] ,
        baseName  toto
      }
   }
  ```

- ```
    application {
      config {
       // still works
        languages [en, fr] , baseName  toto
      }
   }
  ```

If you don't mind minor **breaking changes** in the future, and cleaning it up later that is fine.
Someone is always going to encounter the edge case, but 99% of users won't notice :smile ...
So it really depends on your priorities right now...

**Comment by MathieuAA** [comment]
@bd82 you're right! Both for the paths and the arrays. I'll do the changes

**Comment by MathieuAA** [comment]
About https://github.com/jhipster/jhipster-core/issues/184#issuecomment-368248521, I need to check if I can just remove it. If the generator allows it, then it should be kept.

**Comment by bd82** [comment]
> About #184 (comment), I need to check if I can just remove it. If the generator allows it, then it should be kept.

I think that is less urgent as it is an existing quirk versus introducing a new quirk in 2.0

**Comment by bd82** [comment]
> @bd82 you're right! Both for the paths and the arrays. I'll do the changes

Great 😄 if you wrap the "freeStyle" with some delimiters (quotes/doubleQuotes/whatever)
We would avoid adding technical debt before the future migration. 👍 

e.g:
```JavaScript
    application {
      config {
        path "./foo/bar.java"
      }
   }
```

**Comment by bd82** [comment]
## Identifiers Syntax Variance 

TODO:

**Comment by bd82** [comment]
TestFramework also needs to be wrapped in brackets:

```
 / TEST_FRAMEWORK SPACE* testFrameworks:[a-z, ]+ SPACE* applicationConfigDecl:applicationConfigDecl {
```

And I think frontendFramework has a case **typo**:
front**E**nd vs front**e**nd (capital E)
```
FRONT_END_BUILDER = 'frontendBuilder'

  / FRONT_END_BUILDER SPACE* frontEndBuilder:[A-z]+ applicationConfigDecl:applicationConfigDecl   {
    return addToApplicationDecl(applicationConfigDecl, 'frontEndBuilder', frontEndBuilder.join(''));
  }
```

**Comment by bd82** [comment]
I'm closing this as I'd like to focus only on the minimal scope for introducing the new Chevrotain parser.
