### ISSUE TITLE
Forbid cases of uni OtO relationships where ownerside gets no field

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#185]
Example:
```
entity A
entity B
relationship OneToOne {
  A to B{a}
}
```

**Comment by ruddell** [comment]
Could we default to using the other entity's name?

This would be more flexible as it should work whether or not the developer specifies the relationship name (which most of the time is already the other entity's name).

**Comment by MathieuAA** [comment]
Yes, good point.Le 25 févr. 2018 22:35, Jon Ruddell <notifications@github.com> a écrit :Could we default to using the other entity's name?
This would be more flexible as it should work whether or not the developer specifies the relationship name (which most of the time is already the other entity's name).
