### ISSUE TITLE
Filtering not working

### ISSUE THREAD

**Issue by Blackdread** [jhipster/jhipster-core#188]
### The issue

Filtering on entities is not fully implemented based on [specifications](http://www.jhipster.tech/entities-filtering/)

For a OneToOne or ManyToOne relation, filters like Equals, In and IsSpecified will work but not GreaterThan, LessThan, GreaterOrEqualThan, LessOrEqualThan.

For a normal field (not a foreign key) (example id), filters like Equals, In and IsSpecified will work but not GreaterThan, LessThan, GreaterOrEqualThan, LessOrEqualThan.

Service class "**QueryService**" of jHipster does not filter all cases greaterThan, lessThan, etc.

Only dates and times works with greaterThan, lessThan, etc, it calls the method "buildRangeSpecification"

### Motivation for or Use Case

All filtering should work for entity fields. It is not normal to not be able to to filter on primary key ID via GreaterThan etc.
It should also allow by default to filter for ManyToOne and OneToOne with GreaterThan, LessThan, GreaterOrEqualThan, LessOrEqualThan.

### Reproduce the error

A simple app with OneToOne, ManyToMany, ManyToOne relations and fields then try to filter id or a referring entity with greaterThan or In or any other that is not supported.

### Related issues

None

### Suggest a Fix

Add more if/else to handle other filtering or use the method "buildRangeSpecification" for types that support range filtering (like int, long, etc)/

### The JDL file

entity Camera {
	name String required minlength(2) maxlength(120)
}

entity CameraParam {
	param String required maxlength(45)
}

relationship OneToOne {
	CameraParam{camera(name) required} to Camera{cameraParam required}
}

---

### Versions 
| JHipster           |
| ------------------ |
| `4.14.1` |

- [x ] Checking this box is mandatory (this is just to show you read everything)

### Code from QueryService

Helper function to return a specification for filtering on one-to-one or many-to-one reference
```
protected <OTHER, X> Specification<ENTITY> buildReferringEntitySpecification(Filter<X> filter,
        SingularAttribute<? super ENTITY, OTHER> reference,
        SingularAttribute<OTHER, X> valueField) {
        if (filter.getEquals() != null) {
            return equalsSpecification(reference, valueField, filter.getEquals());
        } else if (filter.getIn() != null) {
            return valueIn(reference, valueField, filter.getIn());
        } else if (filter.getSpecified() != null) {
            return byFieldSpecified(reference, filter.getSpecified());
        }
        return null;
    }
```

Helper function to return a specification for filtering on one-to-many or many-to-many reference
```
protected <OTHER, X> Specification<ENTITY> buildReferringEntitySpecification(Filter<X> filter,
        SetAttribute<ENTITY, OTHER> reference,
        SingularAttribute<OTHER, X> valueField) {
        if (filter.getEquals() != null) {
            return equalsSetSpecification(reference, valueField, filter.getEquals());
        } else if (filter.getSpecified() != null) {
            return byFieldSpecified(reference, filter.getSpecified());
        }
        return null;
    }
```

**This one is called by the ID field for example by default (so no range filter)**
Helper function to return a specification for filtering on a single field, where equality, and null/non-null conditions are supported.
```
protected <X> Specification<ENTITY> buildSpecification(Filter<X> filter, SingularAttribute<? super ENTITY, X>
        field) {
        if (filter.getEquals() != null) {
            return equalsSpecification(field, filter.getEquals());
        } else if (filter.getIn() != null) {
            return valueIn(field, filter.getIn());
        } else if (filter.getSpecified() != null) {
            return byFieldSpecified(field, filter.getSpecified());
        }
        return null;
    }
```

**By default for Instant field type it will call this method**
Helper function to return a specification for filtering on a single Comparable, where equality, less than, greater than and less-than-or-equal-to and greater-than-or-equal-to and null/non-null conditions are supported.
```
protected <X extends Comparable<? super X>> Specification<ENTITY> buildRangeSpecification(RangeFilter<X> filter,
        SingularAttribute<? super ENTITY, X> field) {
        if (filter.getEquals() != null) {
            return equalsSpecification(field, filter.getEquals());
        } else if (filter.getIn() != null) {
            return valueIn(field, filter.getIn());
        }

        Specifications<ENTITY> result = Specifications.where(null);
        if (filter.getSpecified() != null) {
            result = result.and(byFieldSpecified(field, filter.getSpecified()));
        }
        if (filter.getGreaterThan() != null) {
            result = result.and(greaterThan(field, filter.getGreaterThan()));
        }
        if (filter.getGreaterOrEqualThan() != null) {
            result = result.and(greaterThanOrEqualTo(field, filter.getGreaterOrEqualThan()));
        }
        if (filter.getLessThan() != null) {
            result = result.and(lessThan(field, filter.getLessThan()));
        }
        if (filter.getLessOrEqualThan() != null) {
            result = result.and(lessThanOrEqualTo(field, filter.getLessOrEqualThan()));
        }
        return result;
    }
```

**Comment by MathieuAA** [comment]
Hi! this is not the project for such an issue. Post this in the generator's issue tracker instead. Thank you.
