### ISSUE TITLE
Move the module.exports up

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#195]
Like everywhere else in the code.
The point is to know what the file exports without having to scroll down the entire length of the file.

**Comment by bd82** [comment]
I did it but it reduces consistency because it cannot be done for variables / classes that are exposed.
So you end up with some modules exposing at the top and some at the bottom.

**Comment by MathieuAA** [comment]
Okay, I'll review everything tomorrow and find a solution for what you said... I'll merge the maximum now.
