### ISSUE TITLE
Possible improvements for the new parsing system

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#203]
1. Customize the Error Messages Text.
   - Provide Labels in createToken to customize the default error messages.
     * From: ```Expecting token of type --> EQUALS <-- but found --> 'String' <--```
     * To: ```Expecting token of type --> "=" <-- but found --> 'String' <--```
       
   - Evaluate custom error messages structure.
     https://github.com/SAP/chevrotain/blob/master/examples/parser/custom_errors/custom_errors.js
   
   - Evaluate providing specific err messages to certain CONSUME calls.
     https://github.com/SAP/chevrotain/blob/master/examples/parser/custom_errors/custom_errors.js#L81   
     
2. Provide An LSP/Editor friendly API
   - Enable Error Recovery.
   - Expose the CST directly not the AST (e.g. to construct a code formatter / a prettier plugin).
   - evaluate benefits of Modifying the CST to AST builder to handle partial CSTs (when errors occurred).

**Comment by Dufgui** [comment]
Hello @MathieuAA ,

could i help you a little on this ?

**Comment by bd82** [comment]
Hello @Dufgui 

This list was originally created by me to list random thoughts while implementing
the new parser and @MathieuAA documented it here.

So I don't know how important these things are to @MathieuAA and what is the priority....

- Adding labels for better error messages should be pretty simple.
  But it was already done for most tokens automatically.
  *  https://github.com/jhipster/jhipster-core/blob/chevrotain-migration/lib/dsl/lexer.js#L60-L63

- LSP (Language Service Protocol) may not be relevant as the JHipster IDE is
   using XText (implemented by @colameo )

   - Some Language Services capabilities may be relevant for the JDL-Studio project by @deepu105 
      (auto complete, syntax highlights, error recovery), but wrapping in the LSP (Protocol) just for that may be over kill.

I think the next(last?) step for the migration is for me to increase code coverage
and then it depends on @MathieuAA for in depth review, additional manual tests(?) and merging
into the master branch.

I hope to finish this later this week (was side tracked by another project). 😄

**Comment by Dufgui** [comment]
coverage seems already really good no ?

Statements   : 96.47% ( 2185/2265 )
Branches     : 90.69% ( 945/1042 )
Functions    : 98.66% ( 517/524 )
Lines        : 96.51% ( 2155/2233 )

**Comment by bd82** [comment]
> coverage seems already really good no ?

Yeah, but I feel safer with even higher coverage after a big change
and it would would require a few mores hours...

**Comment by MathieuAA** [comment]
I've not looked into the coverage report but the tests may need a little refactoring. I'll have a look after my vacationsLe 8 avr. 2018 18:35, Shahar Soel <notifications@github.com> a écrit :
coverage seems already really good no ?

Yeah, but I feel safer with even higher coverage after a big change
and it would would require a few mores hours...

**Comment by MathieuAA** [comment]
And the coverage is not good enough... We can do much betterLe 8 avr. 2018 17:55, Duff <notifications@github.com> a écrit :coverage seems already really good no ?
Statements   : 96.47% ( 2185/2265 )
Branches     : 90.69% ( 945/1042 )
Functions    : 98.66% ( 517/524 )
Lines        : 96.51% ( 2155/2233 )

**Comment by Dufgui** [comment]
Ok so I wait your return and I you can describe the way you want to follow
on the unit test refactoring. I am available to help you. Have a nice
vacations :)

**Comment by MathieuAA** [comment]
@Dufgui @bd82 Hi! I'm slowly acclimating myself back after my vacations. About the coverage %, raising it just to raise it doesn't make any sense so I propose to:
  - Keep on developing and testing (making sure the coverage doesn't fall for the wrong reasons),
  - Adding tests for previously developed things is also important. I'll try to help in the coming days for that.
For the refactoring, it shouldn't take precedence over the development. It can wait.

**Comment by bd82** [comment]
Welcome back @MathieuAA 😃 

I've actually found and fixed some small bugs while raising the coverage and I think only one file left to hit 100% (for the DSL folder) so don't worry I'm not doing it just to hit some arbitrarily KPI.

> Adding tests for previously developed things is also important

What do you mean by this? all the previous per-existing tests are being executed...
Do you mean previously developed features (unrelated to the parser) that have not been properly tested?

**Comment by MathieuAA** [comment]
I think I'm gonna close this one and open one new ticket about LSP, as discussed during the JHipster Conf with the JHipster IDE team.
