### ISSUE TITLE
Incorrect Identifiers regExp

### ISSUE THREAD

**Issue by bd82** [jhipster/jhipster-core#205]
The regExp `/[A-z]/` (upper A lower z) is used many times in the grammar.
I assume it was meant as a shortcut for: /[A-Za-z]/.

Its meaning however is slightly different as:
* "A".charCodeAt(0) --> 65
* "Z".charCodeAt(0) --> 90
* "a".charCodeAt(0) --> 97
* "z".charCodeAt(0) --> 122

So the range 65-122 includes charCodes 91-96 which are **not** letters.
```
> String.fromCharCode(91)
'['
> String.fromCharCode(92)
'\\'
> String.fromCharCode(93)
']'
> String.fromCharCode(94)
'^'
> String.fromCharCode(95)
'_'
> String.fromCharCode(96)
'`'
```

**Comment by colameo** [comment]
I’m aligning the grammar with the new JDL concepts and noticed that as well. Guess too that the identifiers are meant to be /[A-Za-z]/. Please confirm as this affects the IDE JDL plugins.

**Comment by deepu105** [comment]
I would also suggest to use explicit a-zA-Z as the shortcut is not valid
everywhere, for example in vscode, IDE etc
