### ISSUE TITLE
Fixing spaces in the JDL

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#208]
Currently, the following JDL is correct:
```
entity A {
  thingy String pattern(/[A-Z]+/),
  thingy2 String maxlength('42') minlength(41),
  thingy3 String pattern('/[A-Z]+/')
}
```
This is due to this rule:
```
SPACE = ['\n'|'\t'|'\r'|' '|\u2028|\u2029]
```
which allows quotes.
cc @bd82 is it possible with the new parsing system? I'll have to fix it somehow for the PegJS parser.

**Comment by bd82** [comment]
I think this just means using the right pegjs synatx.

```
// BAD
SPACE = ['\n'|'\t'|'\r'|' '|\u2028|\u2029]
// GOOD (I think?)
SPACE = [\n\t\r \u2028\u2029]
```

I don't see a problem implementing the correct whitespace behavior with chevrotain.
I think its already implemented in the migration branch.

**Comment by bd82** [comment]
Actually its implemented slightly differently in the chevrotain branch.
because "\s" is a strict superset of  [\n\t\r \u2028\u2029]

```javascript
createToken({
  name: 'WHITESPACE',
  pattern: /\s+/, 
  // Whitespace insensitivity for the win.
  group: Lexer.SKIPPED,
  line_breaks: true
});
```
