### ISSUE TITLE
@Pattern(regexp = "undefined") in Java code when generate entity using JDL

### ISSUE THREAD

**Issue by dinhnn** [jhipster/jhipster-core#21]
Duplicate from: https://github.com/jhipster/generator-jhipster/issues/3421#issuecomment-219048840

##### **Overview of the issue**

Generate entity with pattern validation
ex:
entity E{
   test String pattern("$\d+^")
}
Result:
class E{
....
@Pattern(regexp = "undefined")
String test;
....
}

##### **JHipster Version(s)** 
JHipster 3.0

##### **Suggest a Fix** 
Edit generators/entity/templates/src/main/java/package/domain/field_validators.ejs
40: -validators.push('@Pattern(regexp = "' + field.fieldValidateRulesPatternJava  + '")');
40: +validators.push('@Pattern(regexp = "' + (field.fieldValidateRulesPattern ? field.fieldValidateRulesPattern.replace(/\\/g, '\\\\') : field.fieldValidateRulesPattern) + '")');

**Comment by MathieuAA** [comment]
Hi, first of all, I'm sorry I didn't answer earlier, I was on holidays and I didn't want to check my mails.
I'll fix it as soon as I can.

**Comment by MathieuAA** [comment]
This will be fixed after some code from JHipster-UML moves here, so in a very short time.
