### ISSUE TITLE
"skipClient Entity" works with "jhipster import-jdl", but fail in JDL-Studio

### ISSUE THREAD

**Issue by danielmenezesbr** [jhipster/jhipster-core#210]
### The issue

"skipClient Entity" works with "jhipster import-jdl", but fail in JDL-Studio.
JDL-Studio needs change to "skipClient for Entity"

---

### Motivation for or Use Case

---

### Reproduce the error

 - Create a JDL [like it](https://github.com/danielmenezesbr/jhipster_oracle_limits_and_skipclient/blob/master/model.jh)  (without the word **for** after skipClient).

 - Import JDL. It's work fine. Look [here](https://gist.github.com/danielmenezesbr/c4839f6db0b9e608da745c784f50463e#file-jhispter_log-L576)

 - When open the [same file](https://github.com/danielmenezesbr/jhipster_oracle_limits_and_skipclient/blob/master/model.jh) into JDL-Studio, it shows `Expected "for" but "A" found. -> line: 20`

- If you try to import a JDL with "skipClient for Entity", the following error occurs:

```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:import-jdl C:\desv\jhipster_oracle_limits_and_skipclient\model.jh
Options:
The jdl is being parsed.
error: An error has occurred:
        SyntaxError
error: Error message:
        Expected "*", "all", ['\n'|'\t'|'\r'|' '| | ], or [A-Z] but "f" found.
error: Position:
        At l.20.
Error: SyntaxError: Expected "*", "all", ['\n'|'\t'|'\r'|' '| | ], or [A-Z] but "f" found.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: [31m[1mERROR![22m[39m
Error while parsing entities from JDL

    at Environment.error (C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\yeoman-environment\lib\environment.js:157:40)
    at error (C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\generator-jhipster\generators\generator-base.js:2064:18)
    at parseJDL (C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\generator-jhipster\generators\import-jdl\index.js:113:26)
    at Object.<anonymous> (C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\yeoman-generator\lib\index.js:399:25)
    at C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\run-async\index.js:25:25
    at C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\desv\jhipster_oracle_limits_and_skipclient\node_modules\yeoman-generator\lib\index.js:400:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

---

### Related issues

---

### Suggest a Fix

Same behavior between `JDL-Studio` and `jhispter import-jdl`

---

### The JDL file

```
entity NucleoEtapaSubtipoProcesso(ne_subtipoproc) {
    posicao Integer required,
    dataInicio LocalDate,
    dataFim LocalDate,
    status Boolean
}

entity SubtipoProcesso {

}

entity ABC {

}

relationship ManyToOne {
    NucleoEtapaSubtipoProcesso{subtipoProcesso required}  to SubtipoProcesso
}

skipClient ABC
```

---

### Versions 

| JHipster           |
| ------------------ |
| `v4.14.3` |

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by colameo** [comment]
related to [isssue-165](https://github.com/jhipster/jhipster-core/issues/165).

**Comment by MathieuAA** [comment]
This is an old one... And it reflects something that needs be changed in JDL Studio. Keeping the tool up-to-date with the JDL updates is not an automatic process and is somewhat painful to do so (my opinion, feel free to try doing it yourselves).
This is not the repo for this issue **but** I'm not going to close this one.

**Comment by DeanPhillipsOKC** [comment]
According to the [JDL Language Reference](https://www.jhipster.tech/jdl/), the "for" is required (or at least referenced) in the skipClient examples.  If not using the "for" in conjunction with "skipClient", is a change (rather than bug) in JDL, can the language reference be updated?

**Comment by MathieuAA** [comment]
I thought I changed it already, I'll clean up.
