### ISSUE TITLE
Location giving error for entity name

### ISSUE THREAD

**Issue by mkysoft** [jhipster/jhipster-core#220]
### The issue

Location keyword giving error if it is used entity name:

> ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-delete-dialog.tsx
> (12,18): Interface 'ILocationDeleteDialogProps' cannot simultaneously extend types '{ location: Readonly<ILocation>; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
>   Named property 'location' of types '{ location: Readonly<ILocation>; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.
> 
> ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-detail.tsx
> (15,18): Interface 'ILocationDetailProps' cannot simultaneously extend types '{ location: Readonly<ILocation>; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
>   Named property 'location' of types '{ location: Readonly<ILocation>; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.
> 
> ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-update.tsx
> (17,18): Interface 'ILocationUpdateProps' cannot simultaneously extend types '{ location: Readonly<ILocation>; loading: boolean; updating: boolean; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
>   Named property 'location' of types '{ location: Readonly<ILocation>; loading: boolean; updating: boolean; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.

---

### Motivation for or Use Case

I haven't got core reason about this issue. I think we need to add this word as reserved.

---

### Reproduce the error

- Create project with React.
- Create entity with Location name.

---

### Related issues

---

### Suggest a Fix

Not use Location as entity name.

---

### The JDL file

```
entity Locationx {
	 locationCode String required minlength(5) maxlength(5),
	 locationName String required minlength(5) maxlength(50)
}
```
---

### Versions 

| JHipster Module | Version |
| ------------------ | ------------------ |
| generator-jhipster | master (5.0.0.beta 1 |
| jhipster-core | 1.4.4 |

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Have you modified the app in any way?Le 8 juin 2018 19:38, Mustafa Kerim Yılmaz <notifications@github.com> a écrit :
The issue

Location keyword giving error if it is used entity name:

ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-delete-dialog.tsx
(12,18): Interface 'ILocationDeleteDialogProps' cannot simultaneously extend types '{ location: Readonly; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
Named property 'location' of types '{ location: Readonly; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.
ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-detail.tsx
(15,18): Interface 'ILocationDetailProps' cannot simultaneously extend types '{ location: Readonly; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
Named property 'location' of types '{ location: Readonly; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.
ERROR in /Users/mytestproj/src/main/webapp/app/entities/location/location-update.tsx
(17,18): Interface 'ILocationUpdateProps' cannot simultaneously extend types '{ location: Readonly; loading: boolean; updating: boolean; }' and 'RouteComponentProps<{ id: number; }, StaticContext>'.
Named property 'location' of types '{ location: Readonly; loading: boolean; updating: boolean; }' and 'RouteComponentProps<{ id: number; }, StaticContext>' are not identical.


Motivation for or Use Case

I haven't got core reason about this issue. I think we need to add this word as reserved.
Reproduce the error

Create entity with Location name.
Related issues


Suggest a Fix

Not use Location as entity name.
The JDL file

entity Locationx {
	 locationCode String required minlength(5) maxlength(5),
	 locationName String required minlength(5) maxlength(50)
}


Versions

JHipster ModuleVersiongenerator-jhipstermaster (5.0.0.beta 1jhipster-core1.4.4
 Checking this box is mandatory (this is just to show you read everything)

**Comment by mkysoft** [comment]
Hi @MathieuAA, I make change only UserDTO for adding fullname in jhipster. When I change this entity name to Locationx, problem solved. I think it is giving error because of react type script.

**Comment by ruddell** [comment]
This comes from RouteComponentProps where `location` is already a prop.  Affects `history` and `match` as well.  
```
export interface RouteComponentProps<P, C extends StaticContext = StaticContext> {
  history: H.History;
  location: H.Location;
  match: match<P>;
  staticContext: C | undefined;
}
```
We could probably change some names in the detail/update components to make this work

**Comment by MathieuAA** [comment]
Yes Jon, this solution seems the best.Le 9 juin 2018 15:30, Jon Ruddell <notifications@github.com> a écrit :This comes from RouteComponentProps where location is already a prop.  Affects history and match as well.
export interface RouteComponentProps<P, C extends StaticContext = StaticContext> {
  history: H.History;
  location: H.Location;
  match: match<P>;
  staticContext: C | undefined;
}

We could probably change some names in the detail/update components to make this work

**Comment by mkysoft** [comment]
There a lot of things for react like this. I think we can add reserved words look like angular for react.

**Comment by MathieuAA** [comment]
Don't think so, they were removed for a reason. Ping @jduboisLe 10 juin 2018 11:07, Mustafa Kerim Yılmaz <notifications@github.com> a écrit :There a lot of things for react like this. I think we can add reserved words look like angular for react.
