### ISSUE TITLE
Annotations for the JDL

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#225]
Concerns the options `dto, pagination, etc.`.
Former issue: #150

**Comment by deepu105** [comment]
@MathieuAA may I suggest we prioritize the chevrotain migration first so that you don't end up doing the grammar twice for pegJs and then for chevrotain. Since JH5 is just out I would say we have enough time to add new features. WDYT?

**Comment by MathieuAA** [comment]
Good point. Let's do chevrotain first.ThanksLe 22 juin 2018 09:45, Deepu K Sasidharan <notifications@github.com> a écrit :@MathieuAA may I suggest we prioritize the chevrotain migration first so that you don't end up doing the grammar twice for pegJs and then for chevrotain. Since JH5 is just out I would say we have enough time to add new features. WDYT?

**Comment by deepu105** [comment]
Yes :)
finally I can start contributing to JDL grammar as well, I do not understand PegJS at all TBH :wink:

**Comment by MathieuAA** [comment]
@deepu105 I did tell that I'd get it done by the week-end, but didn't tell with which parsing system :) It's implemented with the new one.

**Comment by deepu105** [comment]
@MathieuAA I see that you have implemented annotations :confetti_ball: can you update the default JDL sample in JDL studio to use the annotations? it would be cool

**Comment by MathieuAA** [comment]
Will do!
