### ISSUE TITLE
Bundling for use in the JDL Studio

### ISSUE THREAD

**Issue by bd82** [jhipster/jhipster-core#234]
Is this package ever bundled (webpack?) for use in the browser?
If so special care must be taken when bundling Chevrotain grammars.

http://sap.github.io/chevrotain/docs/FAQ.html#WEBPACK

**Comment by deepu105** [comment]
The JDL studio uses the output from the PegJS parser https://github.com/jhipster/jdl-studio/blob/gh-pages/bower.json#L21

So we would need something similar from this one as well to use in JDL studio. 

I totally forgot about this one

**Comment by bd82** [comment]
So we have the following options:

1. Create a Bundled version as part of the jhipster-core npm package.
   * With safe name mangling.
2. Perform safe bundling as part of the JDL Studio project.
   * Feels like a mistake, I am not sure that it should be the studio's concern.
3. Apply grammar [serialization and de-serialization](https://github.com/SAP/chevrotain/tree/master/examples/parser/serialized_grammar) to make the parser insensitive to bundling transformations.

There is a secondary issue that the studio uses bower to manage dependencies so if we need to consume generated artifacts (e.g: jhipster_core.**min.js**) it won't work unless we add those generated files to the source control.
Perhaps it is time for the studio to consume dependencies via npm?

**Comment by bd82** [comment]
@deepu105 @MathieuAA 

How should we proceed here?

**Comment by deepu105** [comment]
Definitely not option 2.

I will prefer option 1, but then it might be tricky as jhipster-core is a nodejs project and packaging the entire thing and importing in a web app will not work unless we use something like browserify.

About the bower issue, one reason I didn't migrate it was the same issue as above I didn't want the entire package, but just a particular file to deal with the grammar validation & parsing.

Another option is to provide the validation & parsing as a REST service from JHipster online.

Another option is to use jdl-ide for the validations and parsing instead of jhipster-core
I'm pinging @jbadeau @colameo team as well for their opinion

**Comment by bd82** [comment]
One option would be to only bundle the [DSL](https://github.com/jhipster/jhipster-core/tree/master/lib/dsl) directory as part of the npm package of JHipster-Core.

That bit only depends on lodash and will provide you with similar functionality (but different new APIs)

**Comment by deepu105** [comment]
That could also work. JDL studio only needs the DSL parser (the one PegJS was providing)

**Comment by bd82** [comment]
@deepu105 I think #240 is complete.

You should probably build the bundle locally (yarn bundle)
and experiment with it.

Also consider additional APIs can be composed / exposed, e.g:
* Parse the JDL without building an AST. (just for syntax errors).
* Parse the JDL and expose the error objects (instead of throwing errors).
* Parse the JDL and run a CST Visitor for formatting it.
* Parse the JDL in "error recovery" mode thus **multiple** errors will be provided not just the first one.
* Combined the **syntactic** content assist with your **own** logic for **semantic** content assist.
* Incrementally parse smaller parts of a full JDL.

I don't know what exactly is the current functionality of the JDL Studio 
nor what is the long term desired functionality.

Also note that many of the things listed above need to be implemented
they are not provided "for free" by Chevrotain, rather Chevrotain provides the **low level** infrastructure make it possible to implement those. (error recovery, incremental parsing / multiple start rules / separation of syntax and semantics / ...)

This should also be considered in the context of using the JDL IDE by @colameo 
to power the JDL Studio (if possible) to avoid duplicate work.

**Comment by bd82** [comment]
Also need to consider if the modifications to the JDL studio needs to be done in **sync**
with the migration to Chevrotain.

Basically if the changes are not trivial you may consider using the previous implementation for a little while (in the studio) as the functionality differences should be very minor and in edge cases scenarios.

**Comment by bd82** [comment]
This was merged in #240
