### ISSUE TITLE
Only have 'required' as validation for textBlobs

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#244]

**Comment by deepu105** [comment]
I'm really glad you are tracking changes in the generator so closely. You
rock!

Thanks & Regards,
Deepu

**Comment by bd82** [comment]
> I'm really glad you are tracking changes in the generator so closely. You rock!

Maybe a single version monoRepo would help automatically keeping everything aligned?

**Comment by deepu105** [comment]
@bd82 I think we discussed this on the main repo a while ago and decided against it since the release process would be much harder and some other issues we figured.

**Comment by bd82** [comment]
> I think we discussed this on the main repo a while ago and decided against it since the release process would be much harder and some other issues we figured.

Good to know this was discussed 👍
