### ISSUE TITLE
JDL validation for app config

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#265]
When creating an application using JDL, the below validations needs to be done and should throw error for invalid cases.

- [ ] Each property should have only acceptable values, same validations as in main generator, like databaseType for example, see https://github.com/jhipster/generator-jhipster/issues/8390#issuecomment-423813516
- [ ] Invalid combinations should not be allowed, user should not be able to specify combinations that the main generator doesnt support

This would mean a lot of logic duplication from the prompts, so a better way would be to move the validations here as reusable methods and use the same from the generator prompts as well

**Comment by MathieuAA** [comment]
The second point is being handled in the BusinessErrorHandler and the AbstractJDLApplication (will be moved to the error handler).
The first point is handled.
The JDLApplication refactoring is, basically, this ticket (and the one about some default values you created).

**Comment by MathieuAA** [comment]
Yes I currently am

**Comment by deepu105** [comment]
Awesome man, you rock.

I have some more ideas to make JHipster more JDL centric, I'll start a
discussion about that soon.

Thanks & Regards,
Deepu

**Comment by MathieuAA** [comment]
Awesome!!

**Comment by deepu105** [comment]
@MathieuAA plz close this if you think its done
