### ISSUE TITLE
Enrich JDL for container sub generators

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#266]
##### **Overview of the feature request**

Enrich JDL with below, so that we can generate config for k8s, docker-compose, openshift and so on. This will result in creating a folder for the type with a .yo-rc.json with this config and then executing the subgen to generate the files.

```
deployment {
    type kubernetes,
    apps [invoice, notification, store],
    directoryPath "../",
    clusteredDbApps [],
    serviceDiscoveryType eureka,
    dockerRepositoryName deepu105,
    dockerPushCommand "docker push",
    kubernetesNamespace default,
    kubernetesServiceType LoadBalancer,
    monitoring elk,
    istio no,
    istioRoute false
}
```

@MathieuAA I would like to work on it so that I can familiarize myself with chevrotain, do you have any objection to this?

**Comment by deepu105** [comment]
@mraible might be interesting to you as well

**Comment by MathieuAA** [comment]
Nop, please do!!

**Comment by deepu105** [comment]
done
