### ISSUE TITLE
Make sure all application properties use the default value as in generator

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#267]
When providing an app config the minimum that should be required is below and every other property should have a default value(same as in the generator)

```
application {
  config {
    baseName: myApp # technically this can also default from folder name, but for let's not do it for now
  }
}
```

**Comment by deepu105** [comment]
@MathieuAA I think you are the best person to do this, will you have time, of course its not urgent

**Comment by deepu105** [comment]
@jdubois plz note I added a bounty on this

**Comment by MathieuAA** [comment]
@deepu105 Hi, it's already done in `ApplicationOptions`.

**Comment by deepu105** [comment]
@MathieuAA I checked, but it doesnt cover every option. Say for example authenticationType etc

**Comment by deepu105** [comment]
ok, sorry just tried the sample above and it works. I guess you assign default for remaining props in some other place. So I'll close this

**Comment by MathieuAA** [comment]
There are two places: the application options files. It contains some defaults (non-business defaults) and concrete classes that assign logical defaults. I'm gonna move everything to the abstract JDL app in 3.4.1
