### ISSUE TITLE
compile issue with react gateway app with uaa after 3.4.0 release

### ISSUE THREAD

**Issue by jsm174** [jhipster/jhipster-core#268]
##### **Overview of the issue**

React gateway with uaa fails to compile after 3.4.0 release.  

Generator commit: https://github.com/jhipster/generator-jhipster/commit/15666aa64c96d3135abde55fa3f8dfa9b0fbc7fe

Given the following JDL:

```
application {
  config {
    baseName uaa,
    applicationType uaa,
    packageName com.example.uaa,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    buildTool gradle
  }
}

application {
  config {
    baseName gateway,
    applicationType gateway,
    authenticationType uaa,
    packageName com.example.gateway,
    uaaBaseName "uaa",
    databaseType no,
    serviceDiscoveryType eureka,
    clientFramework react,
    buildTool gradle
  }
  entities A, B, C, D
}

application {
  config {
    baseName microservicea,
    applicationType microservice,
    authenticationType uaa,
    packageName com.example.microservicea,
    uaaBaseName "uaa",
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    buildTool gradle
  }
  entities A, B
}

application {
  config {
    baseName microserviceb,
    applicationType microservice,
    packageName com.example.microserviceb,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType postgresql,
    serviceDiscoveryType eureka,
    buildTool gradle
  }
  entities C, D
}

entity A {
    data String
}

entity B {
    data String
}

entity C {
    data String
}

entity D {
    data String
}

dto * with mapstruct
service * with serviceClass

microservice A, B with microservicea
microservice C, D with microserviceb
```

And executing the following build command:

```
./gradlew bootWar -Pprod jibDockerBuild
```

results in:

```
ERROR in ./src/main/webapp/app/shared/reducers/index.ts
Module not found: Error: Can't resolve './user-management' in '/Users/jsm174/git/jhipster/react-test-4/gateway/src/main/webapp/app/shared/reducers'
 @ ./src/main/webapp/app/shared/reducers/index.ts 7:0-47 26:20-34
 @ ./src/main/webapp/app/config/store.ts
 @ ./src/main/webapp/app/index.tsx
```

##### **JHipster Version(s)**

```
yarn global remove generator-jhipster
yarn global add file:/Users/jsm174/Downloads/generator-jhipster-15666aa64c96d3135abde55fa3f8dfa9b0fbc7fe
jhipster import-jdl app.jdl
cd gateway
./gradlew bootWar -Pprod jibDockerBuild
```

```
gateway@0.0.0 /Users/jsm174/git/jhipster/react-test-4/gateway
└── generator-jhipster@5.4.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "clientPackageManager": "npm",
    "databaseType": "no",
    "devDatabaseType": "no",
    "enableHibernateCache": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": [
      "en",
      "fr"
    ],
    "messageBroker": false,
    "nativeLanguage": "en",
    "packageName": "com.example.gateway",
    "packageFolder": "com/example/gateway",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "skipClient": false,
    "skipServer": false,
    "testFrameworks": [],
    "websocket": false,
    "baseName": "gateway",
    "applicationType": "gateway",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "clientFramework": "react",
    "buildTool": "gradle",
    "skipUserManagement": true,
    "jhipsterVersion": "5.4.1",
    "cacheProvider": "hazelcast",
    "serverPort": "8080",
    "useSass": true
  },
  "entities": [
    "A",
    "B",
    "C",
    "D"
  ]
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity A {
  data String
}
entity B {
  data String
}
entity C {
  data String
}
entity D {
  data String
}
dto A, B, C, D with mapstruct
service A, B, C, D with serviceClass
microservice A, B with microservicea
microservice C, D with microserviceb

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1 (Apple Git-112)

node: v10.11.0

npm: 6.4.1

yarn: 1.10.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
This happens because [of this code](https://github.com/ruddell/jhipster-core/blob/4cfdbdf6b4b9f818aa09fec9b9c979ea098e7fd7/lib/core/jdl_gateway_application.js#L42-L44), `skipUserManagement` should not be forced for UAA gateways as need the user management client pages to be genenerated.

**Comment by jsm174** [comment]
Would there ever be a case were a uaa gateway wouldn't want user management client pages?

I'll submit a fix, but just wanted to make sure won't break anything else.

In `jdl_gateway_application.js`, from:

```
if (config.authenticationType.uaa || config.authenticationType === ApplicationOptions.authenticationType.oauth2) {
   config.skipUserManagement = true;
}
```

to:

```
if (config.authenticationType === ApplicationOptions.authenticationType.oauth2) {
   config.skipUserManagement = true;
}
```

And remove this entire block in `jdl_gateway_application_test.js`:

```
    context(`when the authentication type is ${ApplicationOptions.authenticationType.uaa}`, () => {
      let jdlApplicationConfig = null;

      before(() => {
        const jdlApplication = new JDLGatewayApplication({
          config: { authenticationType: ApplicationOptions.authenticationType.uaa, jhipsterVersion: '4.9.0' }
        });
        jdlApplicationConfig = jdlApplication.config;
      });

      it('sets the skipUserManagement flag to true', () => {
        expect(jdlApplicationConfig.skipUserManagement).to.be.true;
      });
    });
```

**Comment by jsm174** [comment]
Tested 5.4.2 with the above changes, and the uaa gateway react app does build with working user management.

**Comment by MathieuAA** [comment]
The PR has been merged

**Comment by MathieuAA** [comment]
What's next for this issue?

**Comment by ruddell** [comment]
I opened a PR in the generator to fix the remaining issue
