### ISSUE TITLE
Specify blueprint in JDL

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-core#279]
##### **Overview of the feature request**

It should be possible to declare the blueprint you want to use for generating an application.

##### **Motivation for or Use Case**

Feature parity between creating an application from cli or from JDL.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
Yes this is something that needs to be done at application level

**Comment by deepu105** [comment]
related to https://github.com/jhipster/generator-jhipster/issues/8610

**Comment by MathieuAA** [comment]
I'll enable it tonight
