### ISSUE TITLE
Core objects, and after that

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#28]
The work in the "coreobjects" branch is almost done, save the last object that should encapsulate every other object.
This is a pseudo-roadmap of what needs to be done afterwards:
  - [x] Migrate the JDL parser here;
  - [x] Test it;
  - [x] Migrate the EntityCreator here and adapt it to be able to generate JSON from JDL;
  - [x] Test it and fix some bugs;
  - [x] Expose the generation;
  - [ ] Update every other project that depend on this project.

@deepu105 As I said, it's *almost* done. I think I might be able to merge the branch and migrate the entity creator by the end of the week at worst... I don't have as much time as planned, and tests take a lot of time...

**Comment by deepu105** [comment]
Its ok Mathieu ill wait for your merge

**Comment by MathieuAA** [comment]
@deepu105 I've merged the dslparser branch into master. Only a couple of tests need doing (and a few issues to close ASAP). Can you test the project with your subgen?

**Comment by deepu105** [comment]
If its ready please proceed to release. I might not have time this week to test. Ill do it next week and release a sub gen update

**Comment by MathieuAA** [comment]
Everything's working for me, so I'll make a release tonight after taking care of #26.

**Comment by MathieuAA** [comment]
Closing this as I'm making a release.
