### ISSUE TITLE
Merge on JDL Import

### ISSUE THREAD

**Issue by brunnels** [jhipster/jhipster-core#281]
##### **Overview of the feature request**
Change the `jhipster_entity_exporter` to deep merge the generated json with the current json if it exists.  Similar to how the `MergeJsonWebpackPlugin` does with the i18n files.

##### **Motivation for or Use Case**
This would allow blueprint authors to use the entity configurations to store additional settings or parameters that are not supported by the JDL.  Anything that is supported by the JDL should continue to be maintained in there. 

Additional settings in the entity json works as is now but any changes get overwritten on jdl-import so merging would be much more user friendly.

The primary hurdle would be updating `object_utils::areEntitiesEqual` to only check for JDL supported fields.  Possibly have an AllJdlEntityFields object with all the supported fields and then copy the values from the generated entity and current entity into new AllEntityFields objects before comparing them?

* [x]  Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Sorry for the late answer, I admit I forgot about this issue as I didn't have much time before. I have the JDL exporting to improve right now, but this issue shall be the next priority.
