### ISSUE TITLE
Postgresql does not work in devDatabaseType

### ISSUE THREAD

**Issue by agoncal** [jhipster/jhipster-core#282]
##### **Overview of the issue**

When importing a JDL with a `devDatabaseType` set to `postgresql` we get a:

```
Error: Unknown value 'postgresql' for option 'devDatabaseType'.
ERROR! Error while parsing applications and entities from the JDL Error: Unknown value 'postgresql' for option 'devDatabaseType'.
```

##### **Motivation for or Use Case**

It was working in previous versions (I think JHipster 5.5)

##### **Reproduce the error**

Create a jdl file called `works.jdl` as follow:

```
application {
    config {
        applicationType monolith
        authenticationType oauth2
        baseName sponsoring
        buildTool maven
        cacheProvider ehcache
        clientFramework angularX
        clientPackageManager npm
        databaseType sql
        devDatabaseType postgresql
        prodDatabaseType postgresql
        languages [en, fr]
        nativeLanguage en
        packageName io.epsil.sponsoring
    }
}
```
Now import the file with the following command and check the result:

```
$ jhipster import-jdl /Users/agoncal/Documents/Code/Quantixx/docs/src/main/services/sponsors/db-notworks.jdl
Using JHipster version installed globally
Executing import-jdl /Users/agoncal/Documents/Code/Quantixx/docs/src/main/services/sponsors/db-notworks.jdl
Options: from-cli: true
The JDL is being parsed.
Error: Unknown value 'postgresql' for option 'devDatabaseType'.
ERROR! Error while parsing applications and entities from the JDL Error: Unknown value 'postgresql' for option 'devDatabaseType'.
```

If you just change the `devDatabaseType` to `h2Memory` then it works. When you check the [documentation](https://www.jhipster.tech/jdl/#application_options) it says that `devDatabaseType` can be `h2Disk, h2Memory,  + the prod database type`, so Postgresql should work.

##### **JHipster Version(s)**

v5.6.1

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options: from-cli: true

##### **JHipster Version(s)**

```
/Users/agoncal/Documents/Code/Temp/jhipsternotworks
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.19.1

node: v11.1.0

npm: 6.4.1

yarn: 1.12.1

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
application {
    config {
        applicationType monolith
        authenticationType oauth2
        baseName sponsoring
        buildTool maven
        cacheProvider ehcache
        clientFramework angularX
        clientPackageManager npm
        databaseType sql
        devDatabaseType h2Memory
        prodDatabaseType postgresql
        languages [en, fr]
        nativeLanguage en
        packageName io.epsil.sponsoring
    }
}
```

##### **Browsers and Operating System**

Mac OSX

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@agoncal :

I think it's the same issue than https://github.com/jhipster/generator-jhipster/issues/8760
It should be fixed in jhipster-core: https://github.com/jhipster/jhipster-core/pull/280 with some improvements: https://github.com/jhipster/jhipster-core/commit/28cceaa43c4e863eaa284dc291bbd7241a52eb12

The jhipster-core v3.6.1 should resolve the issue: https://github.com/jhipster/generator-jhipster/pull/8767

**Comment by agoncal** [comment]
Sorry, I didn't look into the `generator-jhipster` issue tracker, for me it was a bug on the JDL parser.

**Comment by pascalgrimaud** [comment]
No problem :)
Waiting the next JHipster release, you can use jhipster-core v3.6.1 for now
