### ISSUE TITLE
Standardize false values for string fields

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#283]
Currently we use a mix of `false` and `no` to disable things. We should have a standard way of doing this with either `false` or `no` everywhere.

For example see `serviceDiscoveryType` and `cacheProvider`
```scala
application {
  config {
    baseName notification,
    applicationType microservice,
    packageName com.jhipster.demo.notification,
    serviceDiscoveryType false,
    authenticationType jwt,
    databaseType mongodb,
    devDatabaseType mongodb,
    prodDatabaseType mongodb,
    cacheProvider no,
    enableHibernateCache false,
    buildTool gradle,
    serverPort 8083
  }
  entities Notification
}
```

**Comment by deepu105** [comment]
I think we should stick with `no` or `none` for falsey values instead of `false`

**Comment by MathieuAA** [comment]
Agreed. This would be a breaking change if we don't handle this right.

**Comment by deepu105** [comment]
its already broken actually, so i'm doing a fix now to restore old behaviour

**Comment by deepu105** [comment]
closed the wrong one

**Comment by MathieuAA** [comment]
This concerns everyone @jhipster/developers. I agree with @deepu105's proposal.
`false` will also be accepted, as long as it concerns a boolean.

If everyone's okay with `no`, please say so :) If you have any objection, please ~~reconsider~~ tell us why.

**Comment by murdos** [comment]
FYI yhere's a related discussion on https://github.com/jhipster/generator-jhipster/issues/8608
For non boolean parameter `none` seems more appropriate.
For boolean parameter I've no problem with `true`/`false`. But if we choose `no`, the opposite value should also be changed from `true` to `yes`.

**Comment by deepu105** [comment]
Booleans can remain true/false, I'm only talking about String with no/none/false

**Comment by murdos** [comment]
@MathieuAA could you do that for JHipster V6? I could handle the changes in generator-jhipster if needed, but I'm not sure how/where things should be changed here.

**Comment by MathieuAA** [comment]
@murdos Yep, I'll find time this week to do it.

**Comment by murdos** [comment]
@MathieuAA : any update on the subject? If you don't have the time, could you tell me where would be the best place in the code to add the standardization of the provided value, as suggested by @deepu105 : 
https://github.com/jhipster/generator-jhipster/issues/8608#issuecomment-431655162

**Comment by MathieuAA** [comment]
Yeah I got side-tracked this past few weeks.
You can create an utils file for this, like `OptionUtils`, that has the method mentioned.

**Comment by MathieuAA** [comment]
I think this is a good time to do it, I want to release JCore v6 (including quite a few breaking changes) and this issue is just yelling at me to get closed.
I'm gonna see what needs to be done for this one.

**Comment by deepu105** [comment]
But since JCore is so integral to JHipster may be we should do breaking
changes in grammar along with next major version of JHipster.

May be first we should merge jcore to Jhipster

**Comment by MathieuAA** [comment]
Agreed.
About the merging: I give up on lerna. It stops parsing a package's commits after a while, giving no clear error message. Maybe someone has to try again, or we could look for other solutions.

**Comment by MathieuAA** [comment]
Closing this in favor of https://github.com/jhipster/generator-jhipster/issues/8608.
