### ISSUE TITLE
Issues with the new deployment syntax

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#285]
@deepu105, can you confirm those?

  - [x] in the `JDLObect` class, there's no stringifying of a deployment inside a JDL object.
  - [x] not sure if `JDLDeployment#toString` works as intended: this method returns something like
```
{
  deploymentType docker-compose,
  appsFolders [tata, titi],
  dockerRepositoryName "test"
}
```
instead of 
```
deployment {
  deploymentType docker-compose,
  appsFolders [tata, titi],
  dockerRepositoryName "test"
}
```

I'll add more if I find anything.
If you confirm those, I'll work on that.

**Comment by deepu105** [comment]
@MathieuAA you are right the stringify is definitely wrong. Good catch

**Comment by MathieuAA** [comment]
@deepu105 The fixes have been committed. Do you need a release?

**Comment by jdubois** [comment]
I'll do a release of the generator tomorrow morning, please keep me updated

**Comment by MathieuAA** [comment]
@deepu105 I'm going to close the issue. If someone finds something, this issue still exists and can be reopened.

**Comment by MathieuAA** [comment]
@jdubois there's a PR in the generator for this issue.

**Comment by deepu105** [comment]
Thanks man much appreciated
