### ISSUE TITLE
jhipster-side-by-side

### ISSUE THREAD

**Issue by co5dt** [jhipster/jhipster-core#288]
##### **Overview of the feature request**

I feel like I'm on a roll, so here it goes:

There was a very interesting presentation at JHipster Conf 2018 called "JHipster side-by-side". Though the presentation was flawed at one or two points, the basic principle is very intuitive. A non-destructive approach for working with jhipster is to extend the generated classes (Repository, Service, RestController, AngularService). All of the mentioned Java classes inject the respective extended classes, the RestController's receive an updated RequestMapping annotation (works perfectly fine with recent Spring versions) and the extended Angular service an updated endpoint URL respectively.

##### **Motivation for or Use Case**

Image doing this for 40+ entities after a weekend-long planning session with your BI and domain experts. It sure is do-able within an hour, yet it is tedious and error-prone. 

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@co5dt please check existing issues first, we are already discussing these https://github.com/jhipster/jhipster-core/issues/277

**Comment by co5dt** [comment]
@deepu105
a) Sorry
b) Though wouldn't have found it by name anyway
c) Awesome
