### ISSUE TITLE
Update spec for IStio

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#295]
Based on https://github.com/jhipster/generator-jhipster/pull/8987

**Comment by DanielFran** [comment]
Impacts:
- istio: should be now true/false since autoinjection will be always available (options no, manualInjection, autoInjection are not needed anymore)
- istioRoute: removed

**Comment by MathieuAA** [comment]
@DanielFran thanks :)

**Comment by desprez** [comment]
Please update online "deployments" documentation 
https://www.jhipster.tech/jdl/deployments
