### ISSUE TITLE
Generated code using JDL fails to compile if an entity is named "Document"

### ISSUE THREAD

**Issue by afillatre** [jhipster/jhipster-core#301]
##### **Overview of the issue**

Given this JDL : 
```
entity Employee
entity Document

relationship OneToMany {
	Employee{docs} to Document{owner required}
}

// Set pagination options
paginate Employee with pagination

// Use Data Transfert Objects (DTO)
dto Employee with mapstruct
dto Document with mapstruct

// Set service options to all except few
service Employee with serviceImpl
service Document with serviceClass

// Set an angular suffix
// angularSuffix * with mySuffix
```
generated code fails to compile because "Document" is an annotation used on this entities, as shown below : 

```
@Document(indexName = "employee")
public class Employee implements Serializable {
[...]
}
```

No import on my "Document" object is present on the class. Instead, the only imported "Document" class is `import org.springframework.data.elasticsearch.annotations.Document;`.

This results in the failing code below : 

```
    public Employee addDocs(Document document) {
        this.docs.add(document);
        document.setOwner(this); // Does not compile !
        return this;
    }
```

I didn't test with any other "reserved" keywords.

##### **Motivation for or Use Case**

The JDL generator does not complain, and generates a code that doesn't compile.

##### **Reproduce the error**

Actually described in overview

##### **Related issues**

None found

##### **Suggest a Fix**

My preferences to resolve this bug would be to : 

- warn the user during JDL validation that an entity is colliding with an existing object (i.e. annotation in this case)
- use the full qualified name of the object during code generation (i.e not blocking the code generation) wherever the colliding object is (in the entity in my case).

Another approach would be to restrict those entity names, but I like it less because this is actually not so a big deal.

##### **JHipster Version(s)**

Only tested on JHipster 5.8.0

##### **JHipster configuration**

```
{
    "generator-jhipster": {
        "promptValues": {
            "packageName": ""
        },
        "jhipsterVersion": "5.8.0",
        "applicationType": "monolith",
        "baseName": "",
        "packageName": "",
        "packageFolder": "",
        "serverPort": "8080",
        "authenticationType": "session",
        "cacheProvider": "ehcache",
        "enableHibernateCache": true,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "postgresql",
        "prodDatabaseType": "postgresql",
        "searchEngine": "elasticsearch",
        "messageBroker": false,
        "serviceDiscoveryType": false,
        "buildTool": "maven",
        "enableSwaggerCodegen": true,
        "rememberMeKey": "",
        "clientFramework": "angularX",
        "useSass": true,
        "clientPackageManager": "npm",
        "testFrameworks": ["cucumber"],
        "jhiPrefix": "jhi",
        "entitySuffix": "",
        "dtoSuffix": "DTO",
        "otherModules": [],
        "enableTranslation": false
    }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Shown above

##### **Browsers and Operating System**

OS X 10.14.3

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by afillatre** [comment]
`Service`, 'Table`, `Column`, `Entity`, `Repository`, `Pattern`, etc. would be valid domain name as well. The thing is using those name would only be a problem in classes that have the related annotation, so use the fully qualified name of the entity in those classes seems to me to be the least invasive method. But a warning in the JDL generation should be created anyway.

**Comment by MathieuAA** [comment]
Isn't `document` in the reserved keywords as well? If that's the case, perhaps there's an issue there.

**Comment by ruddell** [comment]
Document is only reserved for Mongodb, but the `@Document` annotation is used if you enable Elasticsearch which causes the conflict

**Comment by hermitmaster** [comment]
FYI - I ran into the same issue with an entity named `Application`.

**Comment by MathieuAA** [comment]
Is there something that needs to be done here?
