### ISSUE TITLE
Feature request: support for SAP HANA

### ISSUE THREAD

**Issue by breglerj** [jhipster/jhipster-core#306]
* **Overview of the request**

I'd like to enhance JHipster to support SAP HANA as a database type when creating an application.

* **Motivation for or Use Case** 

Recently I've been adding support for SAP HANA to several open source projects like Hibernate, Spring, Liquibase, and others, and I'd like JHipster to support SAP HANA as a database as well.

* **Browsers and Operating System** 

n/a

* **Related issues** 

n/a

* **Suggest a Fix** 

If you accept the feature request, I can contribute the support for SAP HANA.

**Comment by deepu105** [comment]
@breglerj this is not the correct project for the request, anyway, I don't think we have the bandwidth to have this in the core project, I suggest you explore adding it as a module or blueprint and if it gets popular we can consider for the core. https://www.jhipster.tech/modules/marketplace/#/list
