### ISSUE TITLE
Import JDL only finds one entity when matching MS baseName

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#308]
##### **Overview of the issue**
When importing JDL, all declared entities should be imported.

##### **Reproduce the error**
Using the config supplied below, generate a microservice then import the JDL. You can see only one entity is imported (`OrganizationContact`).

##### **Suggest a Fix**
Not sure.  I think it has to do with the `microservice` keyword, as removing the `Organization` entity from there fixes it.  Note that the microservice baseName is also `Organization`

##### **JHipster Version(s)**
v5.8.1 + master

##### **JHipster and Entity configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sb.organization"
    },
    "jhipsterVersion": "5.8.1",
    "applicationType": "microservice",
    "baseName": "Organization",
    "packageName": "com.sb.organization",
    "packageFolder": "com/sb/organization",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "UAA",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": false,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true,
    "messageBroker": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": []
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Organization {
  orgNum String required,
  orgName String required,
  facilityFlag Boolean required,
  localeNum String maxlength(40),
  primaryUrl String,
  activeFlag Boolean required
}
entity OrgUser {
  login String maxlength(40) required,
  facilityFlag Boolean required,
  orgNum String required,
  defaultFctlFlag Boolean required,
  primaryOrgFlag Boolean required
}
entity RoleType {
  roleTypeNum String maxlength(40) required,
  roleTypeDescription String maxlength(100) required
}
entity Role {
  roleNum String maxlength(40) required,
  roleDescription String maxlength(100) required,
  isActive Boolean required,
  refRoleType String maxlength(40) required,
  orgNum String required
}
entity UserRole {
  login String maxlength(40) required,
  roleNum String maxlength(40) required,
  isActive Boolean required,
  orgNum String required
}
entity ContactType {
  contactTypeNum String maxlength(40) required,
  contactTypeDescription String maxlength(140)
}
entity AddressType {
  addressTypeNum String maxlength(40) required,
  addressTypeDescription String maxlength(140)
}
entity OrganizationAddress {
  addressLine1 String maxlength(40) required,
  addressLine2 String maxlength(40),
  addressLine3 String maxlength(40),
  addressLine4 String maxlength(40),
  addressLine5 String maxlength(40),
  addressLine6 String maxlength(40),
  city String maxlength(40),
  state String maxlength(40),
  country String maxlength(40) required,
  zip String maxlength(40),
  phoneNumber String maxlength(20),
  email String maxlength(40),
  faxNumber String maxlength(20)
}
entity OrganizationContact {
  firstName String maxlength(20) required,
  lastName String maxlength(20),
  phoneNumber String maxlength(20),
  email String maxlength(40),
  faxNumber String maxlength(20)
}
relationship OneToMany {
  Organization{orgUser} to OrgUser{userOrgNum(orgNum) required},
  Organization{orgRole} to Role{roleOrgNum(orgNum) required},
  Organization{orgAddress} to OrganizationAddress{addressOrgNum(orgNum) required},
  Organization{orgContact} to OrganizationContact{contactOrgNum(orgNum) required}
}
relationship ManyToOne {
  Organization{parentOrganization} to Organization,
  Role{roletype(roleTypeNum) required} to RoleType,
  UserRole{roletype} to RoleType,
  UserRole{orguser} to OrgUser,
  UserRole{role} to Role,
  OrganizationAddress{addressType(addressTypeNum) required} to AddressType,
  OrganizationContact{contactType(contactTypeNum) required} to ContactType
}

service Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with serviceImpl
microservice Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with Organization
clientRootFolder Organization, OrgUser, RoleType, Role, UserRole, ContactType, AddressType, OrganizationAddress, OrganizationContact with Organization

</pre>
</details>

##### **Browsers and Operating System**
Mac

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Thanks for reporting this, I'll handle it tonight

**Comment by MathieuAA** [comment]
> Not sure. I think it has to do with the `microservice` keyword, as removing the `Organization` entity from there fixes it. Note that the microservice baseName is also `Organization`

Good analysis, by the way

**Comment by MathieuAA** [comment]
Okay, the issue was that the parsing system would consider `OrganisationContact` to be the microservice, where it should have been `Organisation`.
Gonna fix it now

**Comment by MathieuAA** [comment]
@bd82 I think this one may interest you! Apparently, when an entity has the same name as one microservice, the `entityList` is:
  - for a service, every entity & the method (serviceImpl by default)
  - for a MS, every entity (because the method is the amongst the entities!! `organisation`)

The way the method & the entity lists are handled is interesting too:
  - the method is the last entry of the entity list
  - the entity list is modified by removing this last item

This works like a charm when parsing the service (method: serviceImpl), however, as the MS option can take an arbitrary string... well you should have guessed it by now: there seems to be a filtering of duplicates in the entityList that seems to remove the true last item: `Organisation`.

It's quite difficult to explain as I've just got it right by debugging for the last 20 minutes.

**Comment by MathieuAA** [comment]
@ruddell I don't know what I can do here, as the easiest workaround is not to have an entity have the same name as the MS... I'm waiting for Shahar Soel for this one.

**Comment by MathieuAA** [comment]
Closing this and documenting it, https://github.com/jhipster/jhipster.github.io/pull/729.
