### ISSUE TITLE
Remove Rancher from deployment options

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-core#314]
##### **Overview of the feature request**

I have already removed mentions of them in the documentation (https://github.com/jhipster/jhipster.github.io/pull/709) but all references to Rancher in JHCore should be removed.

##### **Motivation for or Use Case**

Remove unavailable options from the application DSL.

##### **Related issues or PR**

- generator: https://github.com/jhipster/generator-jhipster/pull/9368
- docs : https://github.com/jhipster/jhipster.github.io/pull/709

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
I'll do it tonight

**Comment by lyl2008dsg** [comment]
Why did jhipster remove support for rancher?
Are there any considerations?

**Comment by PierreBesson** [comment]
It was not maintained anymore. Also Rancher (the company) seems to have moved to embrace Kubernetes rather than their own orchestrator.
