### ISSUE TITLE
default values for colums

### ISSUE THREAD

**Issue by AleksandrSokolov** [jhipster/jhipster-core#321]
##### **Overview of the feature request**

Add to JDL ability to set default value for the column

entity abstract C {
    String name default "somevalue"
Int name default 5
}

##### **Motivation for or Use Case**

This is implemetation of:
1) one of the option
ALTER TABLE dbo.doc_exz
  ADD CONSTRAINT col_b_def
  DEFAULT 50 FOR column_b;
2) second option - do it in java backend
3) third option - do it in frontend

##### **Related issues or PR**

Don't find

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
It's possible to add it, and that wouldn't be much of an issue.
However, I'm not in favor of adding it.
IMO, a default value is only business-related and the DB's role is to store whatever you want (I'm against giving it more importance).
A business notion should be enforced by the front-end and/or the back-end. And there's the question of how to actually implement it.

I'd like opinions here, @jhipster/developers.

**Comment by deepu105** [comment]
I'm against this as well, adding a default in the generated liquibase file is very trivial and hence this goes against our policy 2 https://www.jhipster.tech/policies/
