### ISSUE TITLE
Add the non-default user roles to JDL and cli utilities

### ISSUE THREAD

**Issue by Eljah** [jhipster/jhipster-core#322]
##### **Overview of the feature request**

Too many applications require much more roles that admin and plain user. At the beginning of jHipster use, many time is spent on developing the best fit entities configuration. After that, the JDL is exported and only then it is good to start jHispter project as non-monolite or with another frontend or something else, but with importing JDL all achievements of the initial experiment are preserved. Except the user roles. They should be created from scratch. 

##### **Motivation for or Use Case**

It is important because i use jHipster in 2 phases: data modelling prototyping and the realistic system build. I'd like pass all data modelling prototyping results to the phase 2.

##### **Related issues or PR**

- [*] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
I simply don't get it.
First of all, the JDL doesn't handle roles/profiles. Furthermore, I didn't understand 
>  After that, the JDL is exported and only then it is good to start jHispter project as non-monolite or with another frontend or something else, but with importing JDL all achievements of the initial experiment are preserved. Except the user roles.

**Comment by Eljah** [comment]
Could you explain why user roles are out of JDL and out of CLI project set up? The important part of any application, but in jHipster we just configure it in several different parts in specific config files. Why don't explicitly ask "how many roles do you want and please specify all of them" during the CLI project initialization?

**Comment by MathieuAA** [comment]
> Could you explain why user roles are out of JDL and out of CLI project set up?

and

>  Why don't explicitly ask "how many roles do you want and please specify all of them" during the CLI project initialization?

Because this is something you don't know beforehand, especially in Agile development teams.

> The important part of any application, but in jHipster we just configure it in several different parts in specific config files.

If you have a better alternative, please do open an issue (in the generator) so that everyone can contribute to the discussion!

**Comment by Eljah** [comment]
Got it about the generator, but still not clear why roles are out of JDL. If we can consider roles to be a subentity of default and always existing User entity, it is not clear what is the idea no to store this info to JDL. User is a special case, but the particular roles of any of this user is not,

**Comment by ruddell** [comment]
I think this falls under [Policy 2](https://www.jhipster.tech/policies/).  It's a [simple change](https://www.jhipster.tech/tips/025_tip_create_new_authority.html) to add some roles manually.
