### ISSUE TITLE
JDL - Deployment with Istio

### ISSUE THREAD

**Issue by mobilecard** [jhipster/jhipster-core#325]
##### **Overview of the issue**

I am having problem when configure deployment with istio in jdl document. 

##### **Motivation for or Use Case**

error: Error message:
        MismatchedTokenException: Expecting --> '}' <-- but found --> 'istioRoute' <--
        at line: 61, column: 3
SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'istioRoute' <--
        at line: 61, column: 3
ERROR! Error while parsing applications and entities from the JDL SyntaxError: Error: MismatchedTokenException: Expecting --> '}' <-- but found --> 'istioRoute' <--
        at line: 61, column: 3

##### **Reproduce the error**

application {
  config {
    baseName bankingGateway
    applicationType gateway
    packageName com.newway.banking.gateway
    serviceDiscoveryType no
    authenticationType jwt
    prodDatabaseType mysql
    cacheProvider hazelcast
    buildTool gradle
    clientFramework react
    useSass true
    testFrameworks [protractor]
  }
  entities *
}

application {
  config {
    baseName banking
    applicationType microservice
    packageName com.newway.banking.microservice
    serviceDiscoveryType no
    authenticationType jwt
    prodDatabaseType mysql
    buildTool gradle
    serverPort 8082
  }
  entities Bank, Branch
}

entity Bank {
    name String required
    fullName String required
    number String required
    numberVerifier String required
    priority Boolean required
}

entity Branch{
    name String required
    number String required
    numberVerifier String required
}

relationship ManyToOne {
   Branch{bank(number) required} to Bank  
}

service Bank, Branch with serviceClass
paginate Bank, Branch with pagination
microservice Bank, Branch with banking

deployment {
  deploymentType kubernetes,
  appsFolders [banking, bankingGateway],
  dockerRepositoryName "paulossjunior",
  serviceDiscoveryType no,
  kubernetesServiceType Ingress,
  istio autoInjection,
  istioRoute true,
  ingressDomain "40.114.117.40.nip.io"
}

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
`istioRoute` is no longer supported
