### ISSUE TITLE
Setting up Jhipster-Core for Azure Pipelines

### ISSUE THREAD

**Issue by Shaolans** [jhipster/jhipster-core#326]
##### **Overview of the feature request**

Since Travis future is now uncertain, we should progressively migrate our CI to Azure Pipelines like we did for the generator or prettier-java.

##### **Motivation for or Use Case**

Travis is not doing well.
Azure Pipelines can have up to 10 parallel jobs (5 for Travis)
The sonar is currently broken [0% coverage](https://sonarcloud.io/dashboard?id=jhipster-core), this is due to the sonar addon on travis. (It can be easily fixed)

##### **Related issues or PR**

I worked on the ci migration and made it worked [here](https://github.com/Shaolans/jhipster-core/pull/9) but the pipeline needs to be configured beforehand:
- Install [sonarcloud extension](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud)
- add a service connection for SonarCloud

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
The first thing you can do, is to init a very simple `azure-pipelines.yml` to this repo.
So it will be easier for me to start to configure Azure.

Similar to: https://github.com/jhipster/prettier-java/pull/199

**Comment by pascalgrimaud** [comment]
Don't forget to add badge to readme, @Shaolans :)

**Comment by Shaolans** [comment]
Thanks ! I almost forgot :+1:

**Comment by Shaolans** [comment]
This is not relevant anymore since we migrated to Github Actions
