### ISSUE TITLE
Update checkForNoDatabaseType to allow Oauth2/OIDC gateways with no database

### ISSUE THREAD

**Issue by jsm174** [jhipster/jhipster-core#328]
##### **Overview of the issue**

According to the PR (https://github.com/jhipster/generator-jhipster/pull/9648), the jhipster generator was updated to support a no database option for Oauth2/OIDC apps.

Support needs to be added allow this same configuration in JDL otherwise the following error will occur:

```
Error: Having no database type is only allowed for microservices without oauth2 authentication type and gateways with UAA authentication type.
ERROR! Error while parsing applications and entities from the JDL Error: Having no database type is only allowed for microservices without oauth2 authentication type and gateways with UAA authentication type.
```

##### **Reproduce the error**

JDL with the following:

```
application {
   config {
      baseName gateway,
      applicationType gateway,
      authenticationType oauth2,
      packageName com.example.gateway,
      databaseType no
      languages [en],
      buildTool gradle
   }
   entities *
}
```

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/jhipster/app/gateway
`-- generator-jhipster@6.0.1

```

##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)

git version 2.17.1

node: v10.15.3

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.16.0

INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The check to be updated is here: https://github.com/jhipster/jhipster-core/blob/460554132fb824b198c7ff193c07b417bf94ce09/lib/exceptions/application_validator.js#L211

Support for no-database with monoliths is also new, so I think all apps now support it?  @cbornet would know for sure.

**Comment by MathieuAA** [comment]
In any case, I'm allowing it right now for @jsm174's case, and I'll keep it open for any update.
Thanks @ruddell for pointing that out

**Comment by cbornet** [comment]
Yes we now support "no database" for all type of apps and auth.

**Comment by MathieuAA** [comment]
@cbornet thanks :)
