### ISSUE TITLE
npm run coverage

### ISSUE THREAD

**Issue by yelhouti** [jhipster/jhipster-core#348]
##### **Overview of the issue**
`npm run coverage` didn't work fork for me, instead I had to use `nyc ... mocha` instead of `nyc ... report`.
Is this used in your CI or somewhere else, or just someone forgot to change it.
For new people on the project it just wastes some of your time.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
`npm run coverage` runs automatically after running `npm run test` via the `posttest` script.  I can see how that can be confusing though.

**Comment by yelhouti** [comment]
@ruddell thankd for the info, but if I'm not wrong report doesn't regenerate the report, it just displays it.
May be `test` should become: `...nyc --reporter=text-summary mocha test` instead of `nyc mocha test`, so that report works as expected

**Comment by MathieuAA** [comment]
Nice find, but I don't get the original issue at first glance. Can you please, next time, provide more details so that we can understand everything right away? thanks.
I'm going to try improving it right now.

**Comment by yelhouti** [comment]
@MathieuAA thanks for fixing, I can assure you I didn't understand fully what way my problem until rudeel explained where it was used. can't explain what I don't know yet :p
