### ISSUE TITLE
Negative integers not supported by jhipster-uml and JDL online editor

### ISSUE THREAD

**Issue by ole108** [jhipster/jhipster-core#35]
This entity declaration

    entity Location {
        longitude Double min(-180) max(180)
    }

generates the following error message in jhipster-uml and in the JDL online editor:
`Expected a space or integer but "-" found. -> line: 2`

Of course a negative integer is as much an integer number as a positive one ...

**Comment by MathieuAA** [comment]
Thanks for reporting this! I'll fix it tonight.

Le 6 juillet 2016 17:06:31 GMT+02:00, Ole Bulbuk <notifications@github.com> a écrit :
>This entity declaration
>
>    entity Location {
>        longitude Double min(-180) max(180)
>    }
>
>generates the following error message in jhipster-uml and in the JDL
>online editor:
>`Expected a space or integer but "-" found. -> line: 2`
>
>Of course a negative integer is as much an integer number as a positive
>one ...
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/35

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
It has been added, thanks again for notifying us  =)
