### ISSUE TITLE
More advanced enums in JDL

### ISSUE THREAD

**Issue by 62mkv** [jhipster/jhipster-core#357]
##### **Overview of the feature request**

Currently, (I know of) only one simple way to define Enums, like: 
```
enum EnvironmentType {
  ARCHIVE, DEV, INTEGRATION, PROD, TEST, UAT, NON_PROD
}
```

I would suggest to add a way to define custom text for each value like 

```
enum EnvironmentType {
  ARCHIVE("archive"), DEV("development"), INTEGRATION("integration"), PROD("production"), TEST("test"), UAT("uat"), NON_PROD("non-prod")
}
```

##### **Motivation for or Use Case**

This is the way it's done idiomatically in Java, so when you try to update the generated enum.java file with such information, it all gets lost after regenerating from JDL (whenever you've added or updated any enum value name), so it's very annoying.

The generated enum might look like this: 

```
public enum EnvironmentType {

    ARCHIVE("archive"),
    DEV("development"),
    INTEGRATION("integration"),
    PROD("production"),
    TEST("test"),
    NON_PROD("non-prod"),
    UAT("uat");

    private String naturalName;

    EnvironmentType(String naturalName) {
        this.naturalName= naturalName;
    }

    public static EnvironmentType fromNaturalName(String naturalName) {
        for (EnvironmentType value : EnvironmentType.values()) {
            if (value.getNaturalName().equalsIgnoreCase(naturalName)) {
                return value;
            }
        }
        return null;
    }

    String getNaturalName() {
        return naturalName;
    }
}
```

I am not sure what could/should be done on the frontend side when enum is defined like that

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gilbrilhador** [comment]
It is possible to generate a enum like this in jdl/jhipster?

enum Estado {
	AC("Acre"),
	AL("Alagoas"),
	AM("Amazonas"),
	AP("Amapá"),
	BA("Bahia"),
	CE("Ceará"),
	DF("Distrito Federal"),
	ES("Espírito Santo"),
	GO("Goiás"),
	MA("Maranhão"),
	MG("Minas Gerais"),
	MS("Mato Grosso do Sul"),
	MT("Mato Grosso"),
	PA("Pará"),
	PB("Paraíba"),
	PE("Pernambuco"),
	PI("Piauí"),
	PR("Paraná"),
	RJ("Rio de Janeiro"),
	RN("Rio Grande do Norte"),
  	RO("Rondônia"),
	RR("Roraima"),
	RS("Rio Grande do Sul"),
	SC("Santa Catarina"),
	SE("Sergipe"),
	SP("São Paulo"),
	TO("Tocantins")
}

When I try to run jphipster I get this error:

Error during import-jdl: Error: MismatchedTokenException: Expecting token of type --> NAME <-- but found --> '"

**Comment by ruddell** [comment]
@gilbrilhador This works as expected with `generator-jhipster` v6.9.x, and fails with v6.8.x, so it was fixed sometime between those versions

**Comment by gilbrilhador** [comment]
Thank you @ruddell !!! I'm with version 6.8.0... I'll try to update.
