### ISSUE TITLE
Add command-line tools for converting from JDL to JSON and JSON to JDL

### ISSUE THREAD

**Issue by mrts** [jhipster/jhipster-core#359]
##### **Overview of the feature request**

Add two command-line tools

- `jdl2json` for converting from JDL to JSON
- `json2jdl` for converting from JSON to JDL

The tools would be available after `npm  install jhipster-core` (although `jhipster-jdl-tools` would be a more apt name for the package).

##### **Motivation for or Use Case**

This would make it possible to use JDL and JDL Studio for modelling in other frameworks besides JHipster; see for example a proposal of using JDL with the Django web framework here: https://github.com/django-extensions/django-extensions/issues/1416. Other frameworks would use JHipster JSON files as input, as JSON is easy to parse, so a command-line tool is needed for JDL to JSON conversion.

Conversion from JSON to JDL would help to convert models from other frameworks to JSON and then to JDL. It would also simplify importing JSON from existing JHipster projects to JDL Studio.

##### Implementation

Implementation is straightforward, here are draft blueprints (just to get the idea through, better error checking and configurability required):

- `jdl2json`
```js
'use strict';

const jhiCore = require('jhipster-core');

const files = process.argv.slice(2);
const jdlImporter = new jhiCore.JDLImporter(files);
const entities = jdlImporter.import().exportedEntities;
console.log(JSON.stringify(entities);
```
- `json2jdl` (quoting [@cbornet](https://github.com/jhipster/jhipster-core/issues/64#issuecomment-251114625)):
```js
'use strict';

const parseJsonFromDir = require('jhipster-core').parseJsonFromDir;

let jdl = parseJsonFromDir('/path/to/jhipster/app/root/dir');
console.log(jdl.toString());
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hi! Interesting idea that you have!
What would the JSON content look like?

**Comment by mrts** [comment]
Thanks :)!

I think the JSON content could be simply an array of entities that have the [existing JSON structure](https://github.com/jhipster/jhipster-sample-app/blob/master/.jhipster/BankAccount.json) with added `name` field for the name of the entity, something like this:

```json
[
  {
    "name": "BankAccount",
    "relationships": [
      ...
    ],
    "fields": [
      ...
    ],
    ...
  },
  {
    "name": "Operation",
    "relationships": [
      ...
    ],
    "fields": [
      ...
    ],
    ...
  }
]
```

And the result should be interoperable with existing `.jhipster` convention, so I would envision a command-line option that would either output a single file as above or multiple files according to ``.jhipster` convention.

**Comment by MathieuAA** [comment]
Hi! I've read the entire thread here and in the django-extensions repo, and I believe that such CL tools shouldn't be there as JCore only is a lib (a provider).

Here are my points:
  - if clients (django-extensions, or any other) want to use what's exported by this repo (JDL, JSON, etc.), they'd have to provide the code to:
    1. use JHipster-Core
    2. deal with possible transformation (transforming the JSON to make it fit the need)
    3. this would be outside this repo
 - if another client wants a YAML output, or an XML one:
    - this project shouldn't handle the maintenance cost
    - this project should always document each change to the API to make evolution consumer code easier

You've already written the code to perform what you need. You just need to create a project that performs such tasks, or include in another project.
I'd be available to help if needed.
