### ISSUE TITLE
Add caffeine option for cacheProvider

### ISSUE THREAD

**Issue by murdos** [jhipster/jhipster-core#364]
##### **Overview of the feature request**

Caffeine is a new option available for cache since JHipster 6.3.0

##### **Motivation for or Use Case**

It should be possible to select this option in JDL

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/pull/10303

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@murdos : Thanks for adding this; seems I've missed this. 😄
