### ISSUE TITLE
ALL option handling in the parser makes the syntax check fail

### ISSUE THREAD

**Issue by Shaolans** [jhipster/jhipster-core#366]
##### **Overview of the issue**

Since the ```all``` option is handled [now](https://github.com/jhipster/jhipster-core/commit/19395457011595d9245bcc8952eecc5e86d3f2c5) as a NAME token. The syntax check is now [failing](https://github.com/jhipster/jhipster-core/blob/master/lib/dsl/api.js#L57) because since this is a NAME token and because of the entityList rule in the parser, it tries to check the name syntax as a entity name. However ENTITY_NAME_PATTERN does not match ```all``` making it fail.

##### **Motivation for or Use Case**

When the jhipster-core is linked to the generator, the tests fails in the generator due to a test using a jdl containing ```service all with serviceImpl```.

##### **Reproduce the error**

Link the jhipster-core (master) on the generator-jhipster (master) and launch the generator tests.

##### **Related issues**

https://github.com/jhipster/jhipster-core/commit/19395457011595d9245bcc8952eecc5e86d3f2c5

##### **Suggest a Fix**

Either revert the all handling back or add the edge case of all option in the syntax checking but we might need to fix some other problems too.

##### **JHipster Version(s)**

Master version

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Thanks for reporting it, I'll fix it before the week-end release
