### ISSUE TITLE
Running jhipster export-jdl <FILE_NAME> ignores the <FILE_NAME> argument 

### ISSUE THREAD

**Issue by poolebu** [jhipster/jhipster-core#391]
##### **Overview of the issue**

Running `jhipster export-jdl <FILE_NAME>` ignores the `<FILE_NAME>` argument and creates an `app.jdl` file .

##### **Motivation for or Use Case**

I was expecting that the file produced would be named  `<FILE_NAME>`. Its documented at the end of the https://www.jhipster.tech/jdl/getting-started, so it should work.

##### **Reproduce the error**

run `jhipster export-jdl model-10_29_2019-2.jh`, produces `app.jdl`

##### **Related issues**

Yes at https://github.com/jhipster/jhipster-core/issues/362

##### **JHipster Version(s)**

Tested with `v6.4.1`

##### **Browsers and Operating System**

```
Windows 10, WSL Ubuntu
```
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
This is happening because the generator doesn't export to a file when calling JCore. A file must be passed [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/export-jdl/index.js#L50).
