### ISSUE TITLE
Add doc about how to contribute

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#393]
For instance:
  - how to modify the grammar (what the files to update are, what purpose do they serve, etc.)
  - the purpose for each folder (maybe adding more doc would just be enough)

**Comment by SudharakaP** [comment]
@MathieuAA : This I think would be helpful. I can help write it down in the README and/or in our website if you could let me know some details of the project structure. 😄

**Comment by MathieuAA** [comment]
Hi @SudharakaP! It's done already :) or at least the significant part of it. My intent here was to close this one, create a GH project and fill it with cards that'd be converted into relevant issues.
If you wanna contribute, I'd be interested in someone helping me on this stuff! An other viewpoint is more than welcome!

**Comment by SudharakaP** [comment]
Willing to help you out for sure. So you mean https://github.com/jhipster/jhipster-core/projects/9 is the new project for these documentation tracking?

**Comment by MathieuAA** [comment]
Yes. As soon as I finish fixing #404 & #432, I'll create cards... You can create cards too by the way! That way, I'll know what's lacking more easily

**Comment by SudharakaP** [comment]
@MathieuAA : Wonderful. I'll add some if and when I think of some ideas. But I was thinking, what might be really useful to start with is a method to test the JCore without creating new releases. This would enable people like me to do a change and test it out easily. Let me think of a method.... 🤔

**Comment by MathieuAA** [comment]
The "npm link" thing works quite well when one wants to check the integration between the generator and JCore. If you're thinking about "how can I test something in particular in JCore", then a test always does the trick for me.
Documenting it would be a good idea.

**Comment by SudharakaP** [comment]
Ah, totally forgot `npm link`. Exactly what I was looking for. Definitely should include in the docs. I've added a card as well. 😄

**Comment by SudharakaP** [comment]
Ah, totally forgot `npm link`. Exactly what I was looking for. Definitely should include in the docs. I've added a card as well. 😄

**Comment by MathieuAA** [comment]
Great!
