### ISSUE TITLE
how to generate unidirectional associationto

### ISSUE THREAD

**Issue by Denis007** [jhipster/jhipster-core#40]
I have a problem,I want use unidirectional associationto relationship to entity,but I can't use jdl to generate it

**Comment by MathieuAA** [comment]
Hi, can you show me how your JDL is formed please? 

Le 11 juillet 2016 05:22:55 GMT+02:00, Denis007 <notifications@github.com> a écrit :
>I have a problem,I want use unidirectional associationto relationship
>to entity,but I can't use jdl to generate it
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/40

-- 
Mathieu ABOU-AICHI

**Comment by Denis007** [comment]
My jdl is this
relationship OneToMany{
	Node{machine} to Machine
}

when generate the machine entity hava
@ManyToOne
@JoinColumn(name = "node_id")
 private Node node;

**Comment by MathieuAA** [comment]
As far as I know, JHipster only has bidirectional OneToMany relationships (don't know if this has changed though, gotta test). You didn't have any warning message? What tool did you use to parse the JDL?

**Comment by Denis007** [comment]
ok,thank you reply, I find the relationship doc https://jhipster.github.io/managing-relationships/,This type of relationship is not provided by default in JHipster at the momen

**Comment by MathieuAA** [comment]
Yeah... but if the doc's not up-to-date, my entity generation services aren't either. I'm going to test this case tonight.
