### ISSUE TITLE
Exported JDL Cannot be Imported due to Syntax Issues

### ISSUE THREAD

**Issue by hepaestus** [jhipster/jhipster-core#405]
After creating my JDL File and importing it I then used Jhipster to generate a JDL file. My Hope is that they would be the same. They ARE NOT.  Some of my JDL imported relationships are NOT IN THE Generated JDL File.

ALSO, Upon generation you cannot then import the JDL into Jhipster as it fails for syntax issues. Not all of the generated fields are recognized.

**Comment by MathieuAA** [comment]
Transferring this form the generator for investigations

**Comment by MathieuAA** [comment]
@hepaestus Hi again, do you have a sample so that I can test this issue?

**Comment by MathieuAA** [comment]
Closingt this as no information has been given
