### ISSUE TITLE
JDL ManyToMany is imported as OneToOne

### ISSUE THREAD

**Issue by dgorsuch5** [jhipster/jhipster-core#42]
The following sample JDL is imported as a OneToOne relationship in the class files with jhipster 3.5.1. The json files are created with the correct relationship. To reproduce start with a fresh jhipster project and import the below JDL. See that both Car and Driver classes are generated with OneToOne relationships.

entity Driver
entity Car

relationship ManyToMany {
  Car{driver} to Driver{car}
}

**Comment by MathieuAA** [comment]
One would think it's a generator's bug here.... Gotta test.

**Comment by MathieuAA** [comment]
I didn't see any issue at all... For the record, I just pulled master and used it.
Here are all the snippet from the generated files.
```
@Entity
@Table(name = "car")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Car implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToMany
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    @JoinTable(name = "car_driver",
               joinColumns = @JoinColumn(name="cars_id", referencedColumnName="ID"),
               inverseJoinColumns = @JoinColumn(name="drivers_id", referencedColumnName="ID"))
    private Set<Driver> drivers = new HashSet<>();
```

```
@Entity
@Table(name = "driver")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Driver implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ManyToMany(mappedBy = "drivers")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Car> cars = new HashSet<>();
```

**Comment by MathieuAA** [comment]
Did you pull from master, or used the release?

**Comment by dgorsuch5** [comment]
I'm using the release. This is what I have generated:

@Entity
@Table(name = "driver")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Document(indexName = "driver")
public class Driver implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @OneToOne(mappedBy = "driver")
    @JsonIgnore
    private Car car;

**Comment by dgorsuch5** [comment]
Retried it from master and it works as expected.
