### ISSUE TITLE
JDL Entities DataTypes

### ISSUE THREAD

**Issue by aderhmC** [jhipster/jhipster-core#431]
Why I cannot do this:

`entity Example {
	
	aValue String
	aValue String
	aValue EcoLam

}

entity EcoLam {

	aValue String
	aValue String
	//...

}`

**Comment by MathieuAA** [comment]
I don't understand what you mean, and this is not the place for questions (but for bugs/feature requests).
You probably want relationships.
Next time, read the docs.
