### ISSUE TITLE
Add ByteBuffer and ZonedDateTime as field types for cassandra DB

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#433]
Original issue: https://github.com/jhipster/generator-jhipster/pull/11384

What to do:
  - [x] Add the types in the relevant file (field_types.js)
    - and the constraints
  - [x] Update the doc page

**Comment by MathieuAA** [comment]
It's all yours @SudharakaP. Don't hesitate to ping me if you need anything

**Comment by SudharakaP** [comment]
@SudharakaP : Thanks much. Will do 😄

**Comment by SudharakaP** [comment]
Added a preliminary PR, but might be totally off on this one. Let me know if you see any issues. :smile:

**Comment by MathieuAA** [comment]
Thanks! Just a tiny change left and it's good to go!

**Comment by SudharakaP** [comment]
@MathieuAA : Thanks for the review. Corrected. 😄
