### ISSUE TITLE
Add the possibility to allow blueprints to add custom keywords

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#448]
For instance, for the VueJS blueprint, it can add the `clientFramework` value `vuejs`

@pascalgrimaud this one deserves a bounty

**Comment by mshima** [comment]
@MathieuAA are you working on this one?

**Comment by MathieuAA** [comment]
The need for this GH issue is this: I'm a blueprint dev and I don't want the JDL parsing system to throw an error if the JDL content contains any value (option value, app value, anything a blueprint can add) related to the blueprint.
A simple example so that you get the full picture: the vuejs blueprint adds the "vuejs" (or Vue, I don't remember) app value for the "client framework" option. Pierre had to add the string as a valid value back then, but this isn't a good solution as you can guess...

The issue is a possible solution, but it's not definitive. I'm working on the "add the blueprints keyword" right now, and this issue may or may not be relevant after adding the keyword.
All ideas are welcome.

**Comment by mshima** [comment]
I started to implement this one, because I had an idea on how to implement it.
The concept is done.
I will created a draft PR to you take a look.
If this is already in progress, then I will close it.

**Comment by mshima** [comment]
The blueprint jdl will be loaded like I did at https://github.com/jhipster/generator-jhipster/pull/11337.

**Comment by MathieuAA** [comment]
Alright I'll have a look then!
