### ISSUE TITLE
Inheritance, and 'extends'

### ISSUE THREAD

**Issue by BuonOmo** [jhipster/jhipster-core#46]
I didn’t find any way to do inheritance. It would nice to do it as java does it:
```jh
entity Job {
	jobId Long,
	jobTitle String,
	minSalary Long,
	maxSalary Long
}
entity Barmaid /** extends Job */
entity ProjectManager /** extends Job */
```
I may do it after september if you want but it may take time!

**Comment by deepu105** [comment]
Jhipster doesnt support inhertance yet and hence we cannot support as well for now

**Comment by BuonOmo** [comment]
My bad! I didn’t know that, thank you

**Comment by MathieuAA** [comment]
@BuonOmo If you want to propose a PR for this in the generator first, that would be nice =)

**Comment by jdubois** [comment]
I'm not a big fan of inheritance in JPA:

- Lots of performance issues, depending on what you do
- Makes our generator a lot more complex

So for me we should stick to "normal" entities, and if people want inheritance, they need to refactor their entity (and decide which inheritance option they want, and good luck with the performance issues!).

**Comment by BuonOmo** [comment]
@MathieuAA I think I’m not yet good enough to do it, and if there is a lack of performance, maybe I won’t use it neither for my own projects.
I’ll have to get informations on JPA inheritance before I do anything.

**Comment by CarreraPHP** [comment]
@jdubois  @deepu105 , Is there any change of plan for 'inheritance support'. I have a necessity of creating multiple Entities with at least 5 fields common between. Enabling inheritance will help me in moving those fields to a separate entity class and other entities to inherit from it.

If u have a workaround for the same, please let me know.

**Comment by deepu105** [comment]
@CarreraPHP we have some plans but nothing concrete at the moment so I wont be able to give any ETA

**Comment by jdubois** [comment]
I just had feedback from a project which forked JHipster and implemented inheritance: they found it cumbersome, and not better than doing it "manually" on a normal JHipster project. And so they are stopping this.
So I'm really not sure it's a good idea.

**Comment by MathieuAA** [comment]
Let's drop it and let users implement it themselves if they want to.

**Comment by JesusTheHun** [comment]
Anything new on this topic ?

**Comment by gcontini** [comment]
Pity it's closed... maybe inheritance is complex , but implementing everything as separate entity is a serious limitation. Older mda tools (AndroMDA) took the pain of implementing it. seem we're stepping back.

**Comment by jdubois** [comment]
That's a 2 year old ticket, as far as I understand there are new discussions on this topic for JHipster 7.
Then, this would only work for some of your Java code (not for REST endpoints, and of course it's limited to Java).
