### ISSUE TITLE
Inconsistency between JHipster prompt defaults and JDL defaults

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/jhipster-core#464]
The current default for serviceDiscoveryType for JDL-generated UAA apps is none ([related code](https://github.com/jhipster/jhipster-core/blob/4aa2737d07c5a94a20ee38c391ac74444595ae6a/lib/core/jhipster/default_application_options.js#L169)), you can verify this by looking at the .yo-rc.json file generated in the UAA app folder. This is a difference between the JHipster prompt defaults and JDL defaults, an issue can be opened about this on the jhipster-core Github.

The simple fix is to set serviceDiscoveryType eureka in the UAA app JDL configuration.

source: https://stackoverflow.com/a/61804565/9765833

JHipster info (unneed, but still):

INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/michele
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

git version 2.20.1

node: v10.16.0

npm: 6.9.0

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.25.4, build 8d51620a

INFO! Congratulations, JHipster execution is complete!

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Ah thanks!! Do you want to make a PR for that? If not, I'll make it tomorrow
