### ISSUE TITLE
TypeError: Cannot set property 'clientRootFolder' of undefined

### ISSUE THREAD

**Issue by mmarimuthu** [jhipster/jhipster-core#466]
I created a microservice in jhipster create Application.
Created a jdl and attached the same to it.
When running the jhipster import-jdl <myjdl file> it raninto issue. 
Checked the https://github.com/jhipster/jhipster-core/issues/252 but couldn't resolve it.

Attaching the yorc and jh file for reference
[jh.txt](https://github.com/jhipster/generator-jhipster/files/4638790/jh.txt)
[yo_rc.txt](https://github.com/jhipster/generator-jhipster/files/4638791/yo_rc.txt)

Error:

![image](https://user-images.githubusercontent.com/28609408/82125685-3d3d4b00-97c5-11ea-9bea-a0766f98a2c7.png)

Could not get an example with jdl for micoservice in official website. 

---

_edit _

JDL:
```
application {
  config {
    packageName com.ecab.driver
    baseName driverService
    applicationType microservice
    serverPort 3020
    serviceDiscoveryType eureka
    authenticationType jwt
    buildTool maven
    cacheProvider no
    devDatabaseType postgresql
    prodDatabaseType postgresql
    skipClient true
    // more configuration options goes here
  }
  // filter entities here
  entities User, Driver, CarDetails
}

entity User {
	firstName String required
    lastName String
    email String required
    gender String
    address1 String
    city String
    state String
    zipcode String
    country String
    type String required
    mobile String required
}

entity Driver {
    id String
    idProof String
    status String
}


entity CarDetails {
	id String required
	number String required
	model String
	manufacturer String
	type String required
	driverId String
	status String
	currentTripId String
}

relationship OneToOne {
	Driver{user} to User
    Driver{carDetails} to CarDetails
}

microservice all with driverService

service all with serviceImpl 

clientRootFolder all with driverService
```

.yo-rc.json file:
```json
{
  "generator-jhipster": {
    "applicationType": "microservice",
    "gitCompany": "",
    "baseName": "driverService",
    "packageName": "com.ecab.driver",
    "packageFolder": "com/ecab/driver",
    "serverPort": "3020",
    "serviceDiscoveryType": "eureka",
    "authenticationType": "jwt",
    "uaaBaseName": "../uaa",
    "cacheProvider": "no",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "enableSwaggerCodegen": false,
    "messageBroker": false,
    "buildTool": "maven",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientFramework": "angularX",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "6.8.0",
    "jwtSecretKey": "SECRET",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1589648160634,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  },
  "git-provider": "GitHub",
  "git-company": "mmarimuthu",
  "repository-name": "driver-service",
  "entities": [
    "User",
    "Driver",
    "CarDetails"
  ]
}
```

**Comment by MathieuAA** [comment]
It will be fixed in JHipster v6.9.0

**Comment by mmarimuthu** [comment]
@MathieuAA what is the temporary solution

**Comment by MathieuAA** [comment]
As a workaround, you can use `clientRootFolder Driver, CarDetails` explicitely. Or completely omit the option! this is automatically setup if you have the microservice option

**Comment by mmarimuthu** [comment]
@mmarimuthu thanks I will check and get back

**Comment by mmarimuthu** [comment]
@MathieuAA Still the error persists. Could you help.

**Comment by MathieuAA** [comment]
Alright, I need the modified JDL. Have you removed the microservice option and the redundant JDL app?

**Comment by MathieuAA** [comment]
Keeping the microserviceName option is good though

**Comment by mmarimuthu** [comment]
@MathieuAA as per your comments i removed the existing jdl app and tried. It worked. Thanks for the the help..!!

**Comment by MathieuAA** [comment]
Glad I could help, thanks for reporting the issue. If you need explanations on why this works, I'd be happy to detail everything.

**Comment by mmarimuthu** [comment]
@MathieuAA yes, Please provide a link if there is one. Also, my suggestion is that it will be helpful for the developers when we have a detailed 'Hello world' app steps. May be in https://www.jhipster.tech/
And description about the JDL file supported properties.

**Comment by MathieuAA** [comment]
I should improve the docs on that part...
Your example could have been improved because:
  - there was a `yo-rc.json` file as well as an app definition in the JDL (I suggest splitting the two like `app.jdl` and `entities.jdl`), that can help you avoid some weird issues
  - declaring the JDL app and having the `microserviceName` was redundant because you included the entities in your microservice app
  - the `clientRootFolder` is automatically set if you have the microserviceName option or if you have a microservice app declared

Here, the issue was about something fairly stupid on my part, and thanks to you it's fixed (and released BTW).
