### ISSUE TITLE
JDL should add 'generator-jhipster' prefix to blueprints.

### ISSUE THREAD

**Issue by mshima** [jhipster/jhipster-core#468]
##### **Overview of the issue**

Blueprints jdl options should allow `blueprints [vuejs]` value.
To keep consistency with cli `jhipster --blueprints vuejs`.

And all blueprints should be merged unique by name.

##### **Reproduce the error**

`blueprints [vuejs]` creates
```
blueprints: {
  name: 'vuejs'
}
```
at .yo-rc.json.

Should be 
```
blueprints: {
  name: 'generator-jhipster-vuejs'
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
The name resolving shouldn't be done by this repo IMO.

**Comment by MathieuAA** [comment]
However, if JCore just prefixes "generator-jhipster" **every** blueprint not having this, then okay.

**Comment by MathieuAA** [comment]
Two comments later: I've finally re-read the issue (sorry, I should read issues in the morning). Okay

**Comment by mshima** [comment]
Thanks @MathieuAA.
About merging with .yo-rc.json existing values unique by name?
It's too difficult?

Currently it's overriding .yo-rc.json values.

**Comment by MathieuAA** [comment]
Quite easy I guess. Can't do it today though

**Comment by mshima** [comment]
@MathieuAA no problem.

**Comment by MathieuAA** [comment]
@mshima didn't think about it yesterday: why would we merge?

**Comment by mshima** [comment]
@MathieuAA do you think we should force to set update the jdl too?
```
jhipster import-jdl foo-with-kotlin --blueprints vuejs
jhipster import-jdl foo-updated-with-kotlin
```
The second jhipster import-jdl will remove the vuejs blueprint and create angular files with the existing vuejs files.
Seems right to me to don't require the user to add vuejs to jdl or adding the cli option when regenerating.

**Comment by MathieuAA** [comment]
It's simple. We should remove the `--blueprints` option. Anything that can be overridden by JDL "code" shouldn't be an option.

**Comment by MathieuAA** [comment]
Again, I don't get why we should merge... There should be precedence rules.

**Comment by mshima** [comment]
I am thinking about https://github.com/jhipster/generator-jhipster/pull/11770.
So `jhipster jdl https://github.com/jhipster/jdl-samples/blob/master/library.jh --blueprints vuejs` should export the jdl once the import is done.

**Comment by MathieuAA** [comment]
Again, I don't think it's a good idea to provide blueprints from the CLI instead of providing them from the JDL file.

**Comment by mshima** [comment]
This is related to kickstarting a sample application with user customised options.
https://groups.google.com/d/msg/jhipster-dev/UaV6pQwmYFQ/XGgnkS3aCAAJ

Just forget about this.
