### ISSUE TITLE
Create bulk and fine grained relationships

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#47]
when creating complex models it would be nice to have features to create relationships more efficiently

I would like to propose 2 new ways for this

1) create an alternate syntax to add relationships naturally to entity which java devs would be familiar to, we do this already for enum why not have same support for relationship as well
We can continue to create the other side automatically as we do now and people who want the current syntax can continue using that

```
entity Region {
    regionId Long,
    regionName String
    @OneToOne
    country Country required
}

entity Country {
    countryId Long,
    countryName String
}
```

2) another convenience would be to do multiple declaration like below which would make more sense for our current relationship syntax

```
relationship OneToOne {
    Country{region} to Region
    Location{country} to Country
}

relationship OneToMany {
    Employee{job} to Job
    Location{country} to Country
}

```

@jhipster/developers opinions please

**Comment by sendilkumarn** [comment]
Option 1 👍  much `cleaner` and `precise`

one change if possible `country Country required` -> `Country country required`

**Comment by jdubois** [comment]
Yes option 1 is easier, but aren't we going closer and closer to writing a JPA entity itself? My idea, with the questions, was to simplify this (that's why I was doing bi-directional relationships all the time).
Wild idea: maybe we could generated everything from the JPA entities themselves?

**Comment by MathieuAA** [comment]
The second option is already implemented. And I've already said that I'm against the first because JDL is not Java, and we shouldn't get closer in term of syntax.
Julien, what do you mean by generating everything from the JPA entities?

**Comment by MathieuAA** [comment]
@sendilkumarn, we could invert the field name and type... but that would be a major change (for the users). It's so cheap (in terms of coding and refactoring) a change, I don't mind it.

**Comment by jdubois** [comment]
@MathieuAA as option 1 is looking more and more like a JPA entity, my "wild idea" is to read directly a JPA entity. But the whole point here was to have something simpler, so I'm not sure we're on the right track.

**Comment by deepu105** [comment]
I still dont understand and see any justifications to not get closer to
java? What is the issue if syntax is closer to java, JHipster is a java
project and people who design entity with JDL needs to know JPA modelling
to do it and a syntax closer to that would be more ideal and have better
user experience then inventing and introducing new syntax for people to
learn.

Can anybody give me reason or justification for inventing new syntax?

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
From the beginning the only issue I see with our JDL syntax is that its not
natural to java dev to follow,  I'm taking master classes to a lot of
people and they are finding the syntax weird at first. Of course they are
java devs. If I'm not wrong they are the target audience for JDL and not
javascript or ruby people. So IMO its ok to have a new syntax but atleast
we should make it possible for people to use syntax which they already know
as well if its possible.

Why don't we just vote on it and see what people prefer?

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Also my point is not to read from JPA entities, if we can enchance JDL
syntax to have some more features it will start to look like a JPA entity
without all the boilerplate stuff. And that might be good enough

Thanks & regards,
Deepu

**Comment by sendilkumarn** [comment]
exactly to sum up, it is very difficult to convince people [ both customers / developers ] to shift towards `jhipster` is, there are a lot of changes. 

Again following a separate standard here, will confuse people more.

**Comment by MathieuAA** [comment]
I may have been too quick to express what I meant, sorry. I'm OK with changing the order of the field name and the type. However, what's the point in writing Java in the JDL to find it **unchanged** in the .java file? If you want to write JPA in the JDL, you can easily do it in the Java file (and you should, JPA syntax should not be mixed with the JDL which is descriptive) without calling any tool or generator whatsoever...
Frankly, I find the argument of it being confusing or weird a bit overstretched (to put it mildly)... When people are learning to use JPA annotations and learning how to use them, and learning about Hibernate, one of the first things they feel is confusion. Because there's a lot of magic behind the scenes. But, with time, they learn and know the value of using it instead of writing SQL queries by hand, they learn about caveats and issues and they know how to avoid them. It takes time but people learn... believe it or not.

Finally, because I'm getting increasingly tired of this becoming a habit... If you people want another form of annotation hell, there's a language, which is quite known in the community, it's called **Java**.

**Comment by MathieuAA** [comment]
@sendilkumarn, @deepu105 On a lighter tone, do you tell people to RTFM? Because that may be the issue here :)

**Comment by jdubois** [comment]
@MathieuAA you're going too fast:

- I was just saying we could indeed use the Java entity, and generate everything on top of it. That would be a huge change, and that's why I called it a "wild idea".
- I was also saying we might not be on the right track here, as the idea with JHipster is that we simplify all this. So we have less options than JPA (no inheritance, for example). That doesn't prevent from doing more advanced stuff: those could be options to JHipster, or maybe a job for a new module, and in the end people can still refactor what has been generated. But the strong idea we have from the beginning is that we make it all easy to use for beginners, so anyone can start his project quickly, without pitfalls.

-> in that case, and I guess that's what you want, we should choose option 2

**Comment by MathieuAA** [comment]
Well, option 2 is already implemented and used. A working example is the branch core_integration of JUML, where users will be able to convert XMI to JDL, and this syntax is used (by default).

**Comment by deepu105** [comment]
@MathieuAA I completely disagree with you on that. @jdubois im not suggesting changing JDL or using java here my suggestion is simple make it more natural for people coming from a java background. Any java developer should be familiar with writing entities and relationships and whenever I teach people I start with writing the relationship within the entity and then showing the seperate relationship declaration and I have found it to be easy for people to grasp. You guys are talking as if java and jpa syntax are bad :P
I certainty dont want the entire JPA syntax replicated here but I dont find anything wrong in taking few of it from there. I certainly dont like our current variable name followed by type syntax as well, coz it looks as if we are intentionally trying to have it different from java syntax without any benefit from the syntax of course. 

So if we are planning to progress this we would have to someday come out of our ego and do stuff. I still dont see why having few annotations could be bad

**Comment by deepu105** [comment]
@MathieuAA there is a difference between building user friendly software and saying RTFM to whatever we think is right

**Comment by MathieuAA** [comment]
On no Deepu. Annotations are far from bad! I just cry when I see some form of annotation hell in my models, really.
For the fields, we could invert the name and the type, I don't mind after some consideration... but that's major.
Finally, I agree with you. There's a difference. But if **some** (reading you, one could almost understand you speak of everyone) people don't read the doc, then how is it our problem? The project has 90+ stars, a lot of pull requests, an archive even! It has to be the starting point, always.

**Comment by deepu105** [comment]
OK lets be very clear here

1) I'm not suggesting that we use java or JPA I'm suggesting that we add some familiar ways of doing JPA model to JDL instaed of forcing our users to learn a new syntax
Below is a JPA model I definitely dont want to do this in JDL, as @MathieuAA said if I want the below I can do it directly in java. I want something simpler which can generate this and all other required stuff for me
```
@Entity
@Table(name = "country")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Country implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "country_id")
    private Long countryId;

    @Column(name = "country_name")
    private String countryName;

    @OneToOne
    @JoinColumn(unique = true)
    private Region region;
}
```

I'm suggesting the below which has slight similarity to above but far far simpler and would be more familiar to Java devs and wouldn't require them to learn something new and remember a new syntax
```
entity Country {
    countryId Long,
    countryName String
    @OneToOne
    region Region
}
```

and if we can also make the type and attribute switch like below it would be instantly readable and understandable by any java dev without even having to read the docs, I still dont get the rationale behind the original JDL syntax here given our target users are java devs but thats not the issue as people can easily understand it anyway.
```
entity Country {
    Long countryId
    String countryName
    @OneToOne
    Region region
}
```

So no I'm not trying to say we have to go to java, but since we are Java hipster I dont see whats wrong in following the java conventions here if possible, why do we have to intentionally move away from the java conventions? I just want to make JHipster easier for java people as much as possible. Do remember that its the novice and medium level java devs who find JHipster more useful and they are our major user base. Expert java devs might have their own preferences and JHipster is just something they would try out sometimes and they are just our minor user base. Hence our aim should be to make it easier for our major user base. When I introduce JDL to people many would raise an eyebrow and I could instantly read whats in their mind. They think that we are introducing yet another language/syntax for them to learn. Imagine how nice it would be if I can tell them that they can follow most of Java conventions, I could even say that this is kind of a simplified version of JPA model.


2) I definitely dont want annotation hell, but having one or two wouldn't hurt if it makes the model easier to read
3) whatever way we write JDL the main purpose is to automate and generate an end to end app and not just a JPA model
4) In reality people just dont read the docs, thats the hard fact, look at most our tickets. Most people would just assume that they know it. Its like "how hard can it be?" attitude. I'm not implying that we should bend out of our ways for those. If people do not read docs its their problem. But that doesn't mean that we should make it more difficult that absolutely necessary for people.

Hope I made it clearer

**Comment by deepu105** [comment]
Btw just realized, I wasnt proposing 2 options I was proposing 2 additional ways to declare relationship on top of current syntax.

@MathieuAA btw can you please update the JDL docs with bulk relationship option. Its cool that you have already done it :smile:

**Comment by MathieuAA** [comment]
it already has been Deepu [there](http://jhipster.github.io/jdl/#relationshipdeclaration).

**Comment by deepu105** [comment]
Oh damn I really missed that. Good job

Thanks & regards,
Deepu

**Comment by toolforger** [comment]
Making the syntax similar to JPA might create more confusion than help.
People would "just assume" that JPA-like options are simply copied through, which would usually not be the case because JDL is far more abstract (e.g. JDL declares relationships separately, allowing it to be much more concise, while JPA associates them with fields in POJOs and has to deal with complexity/redundancy from directionality and multi-field keys).

So pretty please do not pretend to be JPA-like. It is using JPA, but it is not JPA.

**Comment by MathieuAA** [comment]
Closing this issue, it's so old I'd have to read it again from the start just to start remembering.
