### ISSUE TITLE
jhipster Pattern does not work properly

### ISSUE THREAD

**Issue by lucke-01** [jhipster/jhipster-core#471]
jhipster pattern does not work properly.

I think this should work the same way you code pattern in java this way you should not have to modify your pattern.

I have this:
```
entity A {
  webUrl String pattern(/^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]/),
}
```

And in my import-jdl i get this:
```
Error during import-jdl: unexpected character: ->/<- at offset: 814, skipped 2 c
haracters.
```

**Comment by MathieuAA** [comment]
@lucke-01 hello there.
> I think this should work the same way you code pattern in java this way you should not have to modify your pattern.
There are two issues here with this opinion:
  - JHipster (and the JDL parsing part) is written in JS, which has a different regexp system than the Java one, so the behaviors will likely never be the same
  - There are more than one backend, not just Java: node, .net, etc.

Here's the fixed JDL:
```
entity A {
  webUrl String pattern(/^(https?|ftp|file):\/\/[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]/),
}
```
