### ISSUE TITLE
JDL annotations should allow strings with spaces and utf-8 characters.

### ISSUE THREAD

**Issue by mshima** [jhipster/jhipster-core#472]
##### **Overview of the issue**

Annotations with spaces inside values like:
```
@entityClassHumanized("Foo Bar")
entity FooBar {
  name String
}
```

Exits with error:
```
error: Syntax error message:
	NoViableAltException: Expecting: one of these possible Token sequences:
  1. [NAME]
  2. [INTEGER]
  3. [DECIMAL]
but found: '"foo bar"'
```

##### **Motivation for or Use Case**

Useful for custom labels.
See https://github.com/jhipster/generator-jhipster/pull/11981

More specifically for utf-8 characters, where generated i18n is almost useless:
```
@entityClassHumanized("Instituição")
@entityClassPluralHumanized("Instituições")
entity Instituicao {
  name String
}
```

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@MathieuAA I was thinking about adding annotations support to application.config like: 
```
aplication {
  @customAnnotation
  config {
    baseName foo
  }
}
```

What don you think?

**Comment by MathieuAA** [comment]
What does it add?

**Comment by mshima** [comment]
A workaround to https://github.com/jhipster/jhipster-core/issues/448
```
aplication {
  @blueprintSpecificConfig
  config {
    baseName foo
  }
}
```

**Comment by mshima** [comment]
@MathieuAA never mind, it's harder than I anticipated:
https://github.com/mshima/jhipster-core/tree/config_annotation.

Can you release 7.3.3 for jhipster 6.10.0?

**Comment by MathieuAA** [comment]
Tomorrow yes! I'll have some free time

**Comment by mshima** [comment]
Great thanks 👍 .

**Comment by mshima** [comment]
Ping @MathieuAA

**Comment by MathieuAA** [comment]
It's done.

**Comment by mshima** [comment]
Sorry, my bad, didn’t saw, thanks.
