### ISSUE TITLE
Refactor reserved keyword check 

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-core#48]
As discussed [here](https://github.com/jhipster/jhipster-core/commit/5aae28c4d4d993b16760e30794e2d58f4063ac5d)

Its in progress

**Comment by MathieuAA** [comment]
What about enums?

**Comment by deepu105** [comment]
Actually enums are currently not checked in JHipster but ideally it should be checked, ill add the check when I switch to use `jhipster-core` for the checks there
