### ISSUE TITLE
Add support for fluent setters

### ISSUE THREAD

**Issue by jdubois** [jhipster/jhipster-core#51]
This follows the merge of https://github.com/jhipster/generator-jhipster/pull/3751

As of JHipster 3.6.0 (unreleased at the time of this writing), we will have fluent setters by default.

This means a few changes in JHipster Core (and maybe the JDL, but I'm not an expert here):

- All entities must have a `"fluentMethods": true` attribute, see [this test entity for example](https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/TestEntity.json)
- For many-to-many relationships, both sides of the relationship must have a `otherEntityRelationshipName` attribute, which is the name of the relationship on the other entity. As you can see also [here](https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/TestEntity.json), this name is by default the name of the current entity

Here is an example, with a many-to-many relationship between Car and Driver, where on purpose I named the relationships with their French names:

__Car__

    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "conducteur",
                "otherEntityName": "driver",
                "relationshipType": "many-to-many",
                "otherEntityField": "name",
                "ownerSide": true,
                "otherEntityRelationshipName": "voiture"
            }
        ],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            }
        ],
        "changelogDate": "20160811114329",
        "dto": "no",
        "service": "serviceClass",
        "entityTableName": "car",
        "pagination": "no"
    }

__Driver__

    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "voiture",
                "otherEntityName": "car",
                "relationshipType": "many-to-many",
                "ownerSide": false,
                "otherEntityRelationshipName": "conducteur"
            }
        ],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            }
        ],
        "changelogDate": "20160811114249",
        "dto": "no",
        "service": "no",
        "entityTableName": "driver",
        "pagination": "no"
    }

**Comment by MathieuAA** [comment]
Hi Julien,

If fluentMethods is true everywhere, anytime, why put it in the JSON? 
For the rest, it's easy stuff. I'll do it in a branch tonight.

Le 11 août 2016 17:25:37 GMT+02:00, Julien Dubois <notifications@github.com> a écrit :
>This follows the merge of
>https://github.com/jhipster/generator-jhipster/pull/3751
>
>As of JHipster 3.6.0 (unreleased at the time of this writing), we will
>have fluent setters by default.
>
>This means a few changes in JHipster Core (and maybe the JDL, but I'm
>not an expert here):
>
>- All entities must have a `"fluentMethods": true` attribute, see [this
>test entity for
>example](https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/TestEntity.json)
>- For many-to-many relationships, both sides of the relationship must
>have a `otherEntityRelationshipName` attribute, which is the name of
>the relationship on the other entity. As you can see also
>[here](https://github.com/jhipster/generator-jhipster/blob/master/travis/samples/.jhipster/TestEntity.json),
>this name is by default the name of the current entity
>
>Here is an example, with a many-to-many relationship between Car and
>Driver, where on purpose I named the relationships with their French
>names:
>
>__Car__
>
>    {
>        "fluentMethods": true,
>        "relationships": [
>            {
>                "relationshipName": "conducteur",
>                "otherEntityName": "driver",
>                "relationshipType": "many-to-many",
>                "otherEntityField": "name",
>                "ownerSide": true,
>                "otherEntityRelationshipName": "voiture"
>            }
>        ],
>        "fields": [
>            {
>                "fieldName": "name",
>                "fieldType": "String"
>            }
>        ],
>        "changelogDate": "20160811114329",
>        "dto": "no",
>        "service": "serviceClass",
>        "entityTableName": "car",
>        "pagination": "no"
>    }
>
>__Driver__
>
>    {
>        "fluentMethods": true,
>        "relationships": [
>            {
>                "relationshipName": "voiture",
>                "otherEntityName": "car",
>                "relationshipType": "many-to-many",
>                "ownerSide": false,
>                "otherEntityRelationshipName": "conducteur"
>            }
>        ],
>        "fields": [
>            {
>                "fieldName": "name",
>                "fieldType": "String"
>            }
>        ],
>        "changelogDate": "20160811114249",
>        "dto": "no",
>        "service": "no",
>        "entityTableName": "driver",
>        "pagination": "no"
>    }
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/51

-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
It can be turned to false with an option, if people don't like it.
Or if it is buggy, which is likely on this first version :-)

Le 11 août 2016 5:32 PM, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :

> Hi Julien,
>
> If fluentMethods is true everywhere, anytime, why put it in the JSON?
> For the rest, it's easy stuff. I'll do it in a branch tonight.
>
> Le 11 août 2016 17:25:37 GMT+02:00, Julien Dubois <

**Comment by MathieuAA** [comment]
I'll add it tonight in a separate branch so that it can be merged when you release.
-- 
Mathieu ABOU-AICHI

**Comment by jdubois** [comment]
You can already merge it: more attributes won't break anything

Le 11 août 2016 6:26 PM, "Mathieu ABOU-AICHI" <notifications@github.com> a
écrit :

**Comment by MathieuAA** [comment]
Alright then!

**Comment by MathieuAA** [comment]
@jdubois, I'll release it before you release v3.6.0 so that the subgen will have this. What's your schedule for v3.6.0?

**Comment by jdubois** [comment]
Should be out soon, we're running out of bugs :-)

**Comment by deepu105** [comment]
ok once Mathew release this, we need to update the new core version in JHipster as well

**Comment by MathieuAA** [comment]
I'll release it tonight. There's one more thing to test.

Le 12 août 2016 06:09:47 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>ok once Mathew release this, we need to update the new core version in
>JHipster as well
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/51#issuecomment-239356922

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
Closing this as v1.1.7 is released.
