### ISSUE TITLE
import-jdl json generation issue with microservice

### ISSUE THREAD

**Issue by brunnels** [jhipster/jhipster-core#53]
Using jhipster 3.5.1.

I'm seeing a problem with the JDL config line used to define the microservice for a table.

Docs say do it like this 

```
entity foo
microservice foo with jhipsterapp
```

In the entity json file this comes through as 

```
{
    "relationships": [],
    "fields": [],
    "changelogDate": "20160815122017",
    "entityTableName": "foo",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "microservice": "jhipsterapp"
}
```

I think this is incorrect and should actually be "microserviceName": "jhipsterapp"

If not on the gateway all the entities are created on the gateway rather than just the frontend.

**Comment by MathieuAA** [comment]
Hi, it has been fixed some time ago, but v3.5.1 must not be up-to-date in that regard...
