### ISSUE TITLE
Extra User Warning

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#54]
When I import the below JDL, I get a warning about User even though User was not referenced.  This is with master version of jhipster which links to v1.1.7 of jhipster-core

```
The jdl is being parsed.
Warning:  An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
Writing entity JSON files.
Generating entities.

```
JDL from Microservice section of documentation:
```
entity A
entity B
entity C

microservice * with mysuperjhipsterapp except C
microservice C with myotherjhipsterapp
```

On a side note, the line `search * with ElasticSearch except C` from the Microservice section of the documentation is considered invalid JDL.

**Comment by deepu105** [comment]
I thought I fixed that warning. Let me check

Thanks & regards,
Deepu

**Comment by ruddell** [comment]
Your right, because I ran `npm link generator-jhipster` in the generator-jhipster project, it didn't update jhipster-core and I still had v1.1.5...  Sorry for the trouble.

`npm WARN skippingAction Module is inside a symlinked module: not running add jhipster-core@1.1.7 node_modules/jhipster-core
`
