### ISSUE TITLE
Pushed over master

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#61]
I was rebasing my local copy of jhipster-core (which turned out to be a clone of this rather than my fork) to submit a fix and I messed something up badly. @MathieuAA I pushed v1.1.8 over your work.  Can you please fix it?  Sorry! I'm so embarrassed...

**Comment by deepu105** [comment]
I dont see any commits from you here. Also do you have write access to this repo?

**Comment by ruddell** [comment]
That's the issue - The latest commit was https://github.com/jhipster/jhipster-core/commit/b20e4cab577719d10e51d3ac7c99ca672604ec8e but I pushed an older version over this.

I had a script that fetches from upstream, rebases, and force pushes (I use it to keep my local generator-jhipster updated to master, commands are from JHipster contributing guide) but the repo was a direct clone instead of my fork.  This means there was no upstream so my older version was pushed over the couple of 1.9.0 commits.  Luckily it's only a few commits

**Comment by deepu105** [comment]
Scripting force push/delete stuff is bad man  :P

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
I think @MathieuAA would have to force push his local repo without doing a pull from this. else we need to restore the repo to this state https://github.com/jhipster/jhipster-core/tree/b20e4cab577719d10e51d3ac7c99ca672604ec8e still the release commit for 1,1,9 and the tag for same will be missing

**Comment by deepu105** [comment]
then there is this as well https://dzone.com/articles/git-tip-restore-deleted-tag

**Comment by MathieuAA** [comment]
First of all, don't worry. Everyone makes mistake, and you kinda just wrote history here so I'd say that's a big thing (and it's pretty awesome when I think of it) =) @deepu105 Leave it to me.
