### ISSUE TITLE
JSON to JDL converter

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-core#64]
Is there any way to convert existing json entities to jdl ?
If not it could be handy to have one for people moving their project to jdl

**Comment by deepu105** [comment]
Its not possible with current code. It would require a reverse parser. Im
not sure if thats worth the effort

Thanks & regards,
Deepu

**Comment by cbornet** [comment]
OK.
Since it's JSON, parsing should be easy and regenerating jdl doesn't look too hard. I'll check it if that's not too much effort.

**Comment by MathieuAA** [comment]
It would actually be easy to do such a thing. @cbornet Do you want to do it?

**Comment by cbornet** [comment]
Yes, I can do it.

**Comment by cbornet** [comment]
Your toString() methods in each jdl class make my life too easy :smile: 
Great job @MathieuAA @deepu105 !

**Comment by MathieuAA** [comment]
Thanks Christophe! 

Le 24 septembre 2016 18:18:52 GMT+02:00, Christophe Bornet <notifications@github.com> a écrit :
>Your toString() methods in each jdl class make my life too easy :smile:
>
>Great job @MathieuAA @deepu105 !
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/64#issuecomment-249373146

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
+1

Thanks & regards,
Deepu

**Comment by cbornet** [comment]
Almost done.
Do you know what angularSuffix option is for ? I don't see it anywhere in the JHipster's code.

**Comment by deepu105** [comment]
```
// This adds support for a `--angular-suffix` flag
        this.option('angular-suffix', {
            desc: 'Use a suffix to generate AngularJS routes and files, to avoid name clashes',
            type: String,
            defaults: ''
        });
```

**Comment by cbornet** [comment]
Yes but where is it used ?

**Comment by cbornet** [comment]
JHipster-core doesn't seem to convert JDL angularSuffix to Json angularJSSuffix. Do you confirm ?

**Comment by deepu105** [comment]
If im not wrong its used in the entity state config to add a suffix to
route names


Thanks & Regards,
Deepu

On Mon, Sep 26, 2016 at 6:41 PM, Christophe Bornet <notifications@github.com

**Comment by MathieuAA** [comment]
Weird. I'll have look at it later today.

Le 26 septembre 2016 15:30:56 GMT+02:00, Christophe Bornet <notifications@github.com> a écrit :
>JHipster-core doesn't seem to convert JDL angularSuffix to Json
>angularJSSuffix. Do you confirm ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/64#issuecomment-249569811

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
Wait. Since when angularJSSuffix is a thing? 

Le 26 septembre 2016 15:30:56 GMT+02:00, Christophe Bornet <notifications@github.com> a écrit :
>JHipster-core doesn't seem to convert JDL angularSuffix to Json
>angularJSSuffix. Do you confirm ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/64#issuecomment-249569811

-- 
Mathieu ABOU-AICHI

**Comment by deepu105** [comment]
Its been there for almost 6 months if not more I guess.

Thanks & regards,
Deepu

**Comment by MathieuAA** [comment]
That's not what I meant Deepu. Since when there's an angularJSSuffix in the JSON entity files? I know it was added a long time ago.

**Comment by deepu105** [comment]
Oh ok. I need to check that


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
For the impatient ones, the awesome script I used to convert my json to jdl file.

```javascript
'use strict';

const parseJsonFromDir = require('jhipster-core').parseJsonFromDir;

let jdl = parseJsonFromDir('/path/to/jhipster/app/root/dir');
console.log(jdl.toString());

```

**Comment by MathieuAA** [comment]
Christophe, why don't you propose a PR in the docs? As a release should happen this week, better be prepared to make it available as soon as the release is... released.

**Comment by deepu105** [comment]
you can add this as a sub gen `jhipster:export-jdl` or as an option flag
`export` to import jdl. I guess sub gen will be cleaner


Thanks & Regards,
Deepu

**Comment by cbornet** [comment]
Of course this will be a subgen. I was waitng for the release bit maybe we could prepare a PR.

**Comment by deepu105** [comment]
you can do PR and we can merge it once core is released :)


Thanks & Regards,
Deepu

On Mon, Oct 3, 2016 at 11:10 PM, Christophe Bornet <notifications@github.com
