### ISSUE TITLE
Mariadb does not check reserved keywords

### ISSUE THREAD

**Issue by ruddell** [jhipster/jhipster-core#66]
If you use MariaDB, it should check the MySQL keywords.   Currently [this check](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/reserved_keywords.js#L13) will always return false because MARIADB isn't a key in the RESERVED_WORDS constant.

`if (type === 'mariadb') type = 'mysql';` fixes it but you might know a better way.

**Comment by MathieuAA** [comment]
@deepu

Le 28 septembre 2016 19:07:38 GMT+02:00, Jon Ruddell <notifications@github.com> a écrit :
>If you use MariaDB, it should check the MySQL keywords.   Currently
>[this
>check](https://github.com/jhipster/jhipster-core/blob/master/lib/core/jhipster/reserved_keywords.js#L13)
>will always return false because MARIADB isn't a key in the
>RESERVED_WORDS constant.
>
>`if (type === 'mariadb') type = 'mysql';` fixes it but you might know a
>better way.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/66

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
cc @deepu105

**Comment by deepu105** [comment]
Ill check tomorrow guys, its an easy fix

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
I think the proper solution would be to either have a set of keywords for MARIADB, for now Im creating a copy of mySQL. @ruddell is that ok? does mariadb have any extra reserved words?

**Comment by MathieuAA** [comment]
@deepu105 good idea

**Comment by ruddell** [comment]
That works, they should be the same.  Thanks!
