### ISSUE TITLE
Type validation in the grammar?

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#67]
The validations are currently checked in the grammar, maybe the types should be too.

**Comment by NKU915** [comment]
If don't need the default id,how can specify the id field(s)? For example,
entity Product{
  productId    String required,
  productType  String required,
  activeFlag   YesOrNoEnum required,
}
How can specify productId as the id for Product? many thanks.

**Comment by MathieuAA** [comment]
As farcas I know, there's no overriding the default id field. You could always map your custom id to the DB table's id.

Le 8 décembre 2016 06:57:49 GMT+01:00, HUHU <notifications@github.com> a écrit :
>If don't need the default id,how can specify the id field(s)? For
>example,
>entity Product{
>  productId    String required,
>  productType  String required,
>  activeFlag   YesOrNoEnum required,
>}
>How can specify productId as the id for Product? many thanks.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/67#issuecomment-265659917

-- 
Mathieu ABOU-AICHI

**Comment by NKU915** [comment]
Got it,thanks.

**Comment by MathieuAA** [comment]
There will be no type validation in the grammar. It should be kept simple.
