### ISSUE TITLE
SOAP service

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-core#69]
Hi,

Even though REST is being used more and more; SOAP is still important especially in enterprises. Do you guys have any plans to add support for soap services:

JDL syntax could be something like

service LibraryService {
    Book* findBooksByTitle(String title);
    Book findBookById(String bookId);
}

**Comment by jdubois** [comment]
- it could be a module, clearly I understand your point and see the interest
- it won't be in the main generator, as our goal is it generate REST services, to be used by AngularJS (and also other technologies), and we are not going to generate everything

**Comment by jbadeau** [comment]
ok

**Comment by deepu105** [comment]
I started a module to do jaxb + springweb services sometime back but didn't
find time to complete it. But yes this is clearly a module material

Thanks & regards,
Deepu
