### ISSUE TITLE
The User entity isn't dealt with correctly

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/jhipster-core#71]
Sample JDL:

```
entity Project
entity Technology

relationship ManyToOne {
    Project{creator} to User,
    Technology{creator} to User,
    Technology{prj} to Project{tech}
}

relationship OneToOne {
    Project{rootTech} to Technology
}

relationship OneToMany {
    Technology{subCreator} to User,
    Technology{subTech} to Technology{parentTech}
}
```

**Comment by deepu105** [comment]
you cant do oneToMany to User its prohibited in jHipster. what is the issue?

**Comment by MathieuAA** [comment]
Just wondered if we could manage that somehow

Le 9 octobre 2016 19:41:59 GMT+02:00, Deepu K Sasidharan <notifications@github.com> a écrit :
>you cant do oneToMany to User its prohibited in jHipster. what is the
>issue?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/71#issuecomment-252500640

-- 
Mathieu ABOU-AICHI

**Comment by MathieuAA** [comment]
But I realized too late this wasn't a bug... thus the confusion.
