### ISSUE TITLE
feature based java packages

### ISSUE THREAD

**Issue by jbadeau** [jhipster/jhipster-core#72]
Hi,

I have seen that the angular codebase is following best practices by organizing code based on features. Is there an plan to do this for the java code as well?

Jose

**Comment by MathieuAA** [comment]
Hi Jose,

Post about it in the generator project please, as it is the only repo dealing with that. Thanks.

Now my 2 cents: it would not be considered standard, as it's convenient to know where each piece of code is located (ie. controllers, models, etc.). It's a kind of implicit convention... Going away from it would not be considered good practice. Others might disagree however, I've experienced that...


Le 10 octobre 2016 18:20:57 GMT+02:00, Jose Badeau <notifications@github.com> a écrit :
>Hi,
>
>I have seen that the angular codebase is following best practices by
>organizing code based on features. Is there an plan to do this for the
>java code as well?
>
>Jose
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/jhipster-core/issues/72

-- 
Mathieu ABOU-AICHI
