### ISSUE TITLE
create entitry field is not null,but swagger say optional

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-core#74]
i creating an entity e.g. `Blog`

jdl code like this
```
entity Blog {
   name String required
}
```

save as jhipster-jdl.jh

`yo jhipster:import-jdl jhipster.jh`

```java
@Entity
@Table(name = "blog")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Blog implements Serializable {
 private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @NotNull
    @Column(name = "name", nullable = false)
    private String name;

    //.....
}
```
but on the swagger(http://localhost:8080/#/docs  admin>API->choose Blog Resource->Model) ,it's optional, like this
![sp20161011_163202](https://cloud.githubusercontent.com/assets/15098916/19263721/4e283778-8fd0-11e6-87d4-cc96cd33877b.png)

i have to change Blog.java

```java
    //...

    @NotNull
    @ApiModelProperty(required=true)
    @Column(name = "name", nullable = false)
    private String name;
    //...
```

**Comment by MathieuAA** [comment]
Closing this as this issue [here](https://github.com/jhipster/generator-jhipster/issues/4308) has not been closed (and it's not the right place to post it...).
