### ISSUE TITLE
How to invoke another microservice application

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-core#75]
i'm newbie in JHipster and i'm trying to figure this, when i create two microservice applications, e.g. micro1,micro2,  how to call each other between micro1 and micro2?
thrift ? grpc-java ? httpclient ? HttpURLConnection ? Sping RestTemplate?

**Comment by anjia0532** [comment]
like  MicroserviceSecurityConfiguration.java ? use the RestTemplate 

```java

@Inject
    @Qualifier("loadBalancedRestTemplate")
    private RestTemplate keyUriRestTemplate;

    private String getKeyFromAuthorizationServer() {
        // Load available UAA servers
        discoveryClient.getServices();
        HttpEntity<Void> request = new HttpEntity<Void>(new HttpHeaders());
        return (String) this.keyUriRestTemplate
            .exchange("http://uaa/oauth/token_key", HttpMethod.GET, request, Map.class).getBody()
            .get("value");

    }

```

**Comment by MathieuAA** [comment]
Hi, this is not the place to post this. Post it in the generator's issue tracker, use the Gitter or post in StackOverflow. Thanks.

**Comment by pascalgrimaud** [comment]
@MathieuAA is right
And there is already a big discussion about this and a lot of interesting links (blog, sample repo, tuto, etc.) here -> https://github.com/jhipster/generator-jhipster/issues/3649

**Comment by MathieuAA** [comment]
Thanks Pascal :)

**Comment by anjia0532** [comment]
@pascalgrimaud @MathieuAA thanks,it's cool,[jhipster/generator-jhipster#3649](https://github.com/jhipster/generator-jhipster/issues/3649)
