### ISSUE TITLE
Required relationship SyntaxError - Jhipster-uml

### ISSUE THREAD

**Issue by AnassTeemo** [jhipster/jhipster-core#76]
Hi!

In order to create a required relationship using JDL, I found ([Here](https://github.com/jhipster/jhipster-core/blob/master/test/test_files/required_relationships.jdl)) that we can do this:

    entity A
    entity B
    
    relationship ManyToOne{
      A{b required} to B
    }

When I run the following command `jhipster-uml myjdlfile.jdl` I get this:

    An error has occurred:
            SyntaxError 
    At line 5, column 6. 
    Error message:
            Expected "}" or a space but "r" found.

Apparently, it doesn't recognize the required .

I am using Jhipster UML v1.6.5 and Jhipster Generator v3.4.0

Plz Help me. I posted this question a week ago in stackoverflow but unfortunately I didn't get a response.

Thanks :)

**Comment by MathieuAA** [comment]
Hi, the state of the master branch is different than the one used in JHipster UML v1.6.5. You have to use the subgen to deal with JDL files (`yo jhipster:import-jdl YOUR_FILE`).

**Comment by AnassTeemo** [comment]
Can I solve this SyntaxError by upgrading my  Jhipster UML?

**Comment by MathieuAA** [comment]
Nop. JHipster UML doesn't deal with JDL anymore. That's why I told you about the subgen.
