### ISSUE TITLE
css change on basis of language

### ISSUE THREAD

**Issue by gshah188** [jhipster/jhipster-core#78]
Hi everyone,

I have configured  Arabic as additional language in my JHipster project.  What I want if user select Arabic language page should load different set of css files e.g., instead of cssfile1.css cssfile2.css should be loaded. Can anyone recommend best practice to do this.

**Comment by gmarziou** [comment]
Hello, this is an issue tracker, a better place for questions or discussions is on stackoverflow or gitter.
