### ISSUE TITLE
Comments in relationships not working

### ISSUE THREAD

**Issue by cbornet** [jhipster/jhipster-core#81]
* JDL to JSON : looks like a bug since there is code to support it
* JSON to JDL : not implemented yet

```
yo jhipster:import-jdl /home/vagrant/workspace/jhipster-core/test/test_files/complex_jdl.jdl
```
Expected to see `"javadoc": "A relationship"` in Department.json but it's not there

**Comment by MathieuAA** [comment]
I didn't know it was the international JHipster issue day!!

**Comment by cbornet** [comment]
I'm reopening because the JDL to JSON conversion still needs to be fixed

**Comment by MathieuAA** [comment]
Oh! Yes of course!
