### ISSUE TITLE
jhipster existing ui code overriting

### ISSUE THREAD

**Issue by Abd-ksr** [jhipster/jhipster-core#86]
I am having working jhipster application and i have modified some of the javascript and html files as per requirements. After applying the the jdl  file (yo jhipster:import-jdl my_file.jdl) it is overwritten the modified  javascript and html files. 

Is there any way i can safeguard the modified files while applying entity through jdl?

**Comment by gmarziou** [comment]
No.
Please don't post questions on the issue tracker, use stackoverflow.
