### ISSUE TITLE
multiple JDL internal comments not allowed in most cases

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/jhipster-core#95]
When writing multiple JDL comments like that
```
// First line of the internal JDL comment
// Second line of the internal JDL comment
```
Then in most cases error is rased because in grammar is almost everywhere used `JDLComment?` not `JDLComment*` and `JDLComment` defines single row comment:
```
JDLComment = "//" [^\n\r]*
```
To implement this enhancement one possible solution is change this block to:
```
JDLComment = JDLCommentLine+
JDLCommentLine = space* "//" [^\n\r]*
```
Another solution is change `JDLComment?` to `JDLComment*` everywhere.

**Comment by MathieuAA** [comment]
Indeed, you're right. I'll make the changes right away. Thanks!

**Comment by MathieuAA** [comment]
Funny thing, PegJS can't properly ignore some input. It just can't, and this has been the case for 5 years. There's only one "clean" solution to do that, and it's implemented in the master branch right now: use `String#replace` to remove the comments.

**Comment by kaidohallik** [comment]
Neat solution. Thanks!
Maybe also polish `grammar.txt` - there are now some places like `SPACE*  SPACE*`, cleaner would by single `SPACE*`.

**Comment by MathieuAA** [comment]
Yeah I know. I'm closing other things first. I always clean up things after I commit.
